### ISSUE TITLE
[question] configure UploadListener and StoragePath via xml

### ISSUE THREAD

**Issue by kleinlain** [Netcentric/accesscontroltool#132]
Hello,

is it possible to enable the UploadListener and setting the Storage Path via osgiConfig xml?

It would be awesome for automation of installations of our docker images if we could simply add tow osgiConfig xmls, with something like

`<?xml version="1.0" encoding="UTF-8"?>
<jcr:root xmlns:sling="http://sling.apache.org/jcr/sling/1.0" xmlns:jcr="http://www.jcp.org/jcr/1.0"
    jcr:primaryType="sling:OsgiConfig" 
    AceUploadListener.setStatusService="enabled"/>`

and the same for AceService.configurationPath

best
/anja

**Comment by gruberroland-netcentric** [comment]
Sure, we use standard OSGI configuration. You can set this via XML config files.

**Comment by kleinlain** [comment]
ok, either I am too stupid or I forgot something essential.

We provide two additional files in our package

/jcr_root/apps.../config

biz.netcentric.cq.tools.actool.configuploadlistener.impl.UploadListenerServiceImpl.xml

`<?xml version="1.0" encoding="UTF-8"?>
<jcr:root 
	xmlns:sling="http://sling.apache.org/jcr/sling/1.0"
	xmlns:jcr="http://www.jcp.org/jcr/1.0"
	jcr:primartyType="sling:OsgiConfig"
	AceUploadListener.setStatusService="enabled" />`

and 
biz.netcentric.cq.tools.actool.aceservice.impl.AceServiceImpl.xml
`<?xml version="1.0" encoding="UTF-8"?>
<jcr:root xmlns:sling="http://sling.apache.org/jcr/sling/1.0" xmlns:jcr="http://www.jcp.org/jcr/1.0"
    jcr:primaryType="sling:OsgiConfig" 
   	AceService.configurationPath="/apps/our/path"/>`

What am I missing here?
