### ISSUE TITLE
Configure Listener and configuration path via osgiConfig

### ISSUE THREAD

**Issue by kleinlain** [Netcentric/accesscontroltool#133]
Not sure if closed issues are read anymore, so...

either I am too stupid or I forgot something essential.

We provide two additional files in our package

/jcr_root/apps.../config

biz.netcentric.cq.tools.actool.configuploadlistener.impl.UploadListenerServiceImpl.xml

<?xml version="1.0" encoding="UTF-8"?> <jcr:root xmlns:sling="http://sling.apache.org/jcr/sling/1.0" xmlns:jcr="http://www.jcp.org/jcr/1.0" jcr:primaryType="sling:OsgiConfig" AceUploadListener.setStatusService="enabled" />

and 
biz.netcentric.cq.tools.actool.aceservice.impl.AceServiceImpl.xml
<?xml version="1.0" encoding="UTF-8"?> <jcr:root xmlns:sling="http://sling.apache.org/jcr/sling/1.0" xmlns:jcr="http://www.jcp.org/jcr/1.0" jcr:primaryType="sling:OsgiConfig" AceService.configurationPath="/apps/our/path"/>

What am I missing here?

**Comment by gruberroland-netcentric** [comment]
Looks good. Maybe you have saved manually in system console? Then the XML is not applied. In this case delete the configuration in system console. Try also a restart of AEM in case something got stuck.

**Comment by kleinlain** [comment]
ah, yes, seems like it was a problem with manual config, I reinstalled the actools bundle with a restart of the instance, now it works configuration seems to work. thanks.
