### ISSUE TITLE
system user path /home/users/system/system/...

### ISSUE THREAD

**Issue by kleinlain** [Netcentric/accesscontroltool#136]
Hi,

when uploading a yaml configuration to a publish instance (aem 6.2), the service users are created, the permissions are set, but the user path is weird because the system folder is duplicated. 

please let me know if this a known issue and if there is any workaround.

**Comment by ghenzler** [comment]
@kleinlain Could you please provide an example configuration fragment?

**Comment by kleinlain** [comment]
`- group_config:

  - serviceusergroup:
  
    - name: dbad serviceuser group
      isMemberOf: everyone
      members:

- user_config:

  - vehiclestoreservice:

    - name: vehiclestoreservice
      isMemberOf: serviceusergroup
      path: system
      isSystemUser: true

- ace_config:

  - vehiclestoreservice:

    - path: /etc/vehiclestore
      permission: allow
      actions: read,modify,create
      privileges:

    - path: '/content/*/*/*/tools/vehiclestore_mapping'
      permission: allow
      actions: read,modify,create
      privileges:`

**Comment by mtstv** [comment]
You must define the full JCR path to the system user folder

- user_config:

    - vehiclestoreservice:
        - name: vehiclestoreservice
          isMemberOf: serviceusergroup
          path: **/home/users/system**
          isSystemUser: true

**Comment by ghenzler** [comment]
@kleinlain Please reopen if problem still exists.
