### ISSUE TITLE
Add dump method for users and groups

### ISSUE THREAD

**Issue by handrez** [Netcentric/accesscontroltool#138]
I'd like to add a method to dump the lists of groups and users to a file, under `/var/statistics/achistory`
Similar to the methods `getCompletePrincipalBasedDumpsAsString` and `getCompletePathBasedDumpsAsString` in `Dumpservice`
Also the method should return a String, similar to the mentioned methods.

**Comment by ghenzler** [comment]
@handrez Why don't you just use `groupBasedDump()` [1] and extract the information that you need?

**Comment by handrez** [comment]
We initially planned to use this function quite frequently, so we wanted to generate the file with only the information we needed. But, we recently changed that plan, so we are ok using the existing functions and then modifying the resulting file, at least for the moment.
