### ISSUE TITLE
can't load yaml files with .yml extension

### ISSUE THREAD

**Issue by EdwinFLopez** [Netcentric/accesscontroltool#150]
I have found that by using the maven plugin, If I set my configuration in yaml files with extension .yml, the tool doesn't load them.
Thanks.

**Comment by jochenkoschorke** [comment]
Hi, is it crucial for you to have .yml as extension? The more common variant IMHO is .yaml and this is also at least what yaml.org is recommending (see: http://www.yaml.org/faq.html). Apart from that it's  also what is used throughout our documentation whenever we refer to configuration files. So, if possible, please use .yaml as extension for your configurations.

**Comment by EdwinFLopez** [comment]
Thanks. No, actually it is not required at all, but explaining that in the readme would have saved me some time this morning :-).
Thanks for the aclaration. I think that if this is documented, the ticked can be closed.

**Comment by jochenkoschorke** [comment]
I don't know which parts of the readme you consulted, but in:

https://github.com/Netcentric/accesscontroltool/blob/develop/docs/Configuration.md#configuration-file-format

there is quite clearly stated that the configuration file suffix is .yaml. 

So, IMHO this information is already contained in a quite obvious way in the documentation.

**Comment by EdwinFLopez** [comment]
Thanks again. Indeed, I read that part, which stated that the extension is "*.yaml", however, It does not explicitly say that it is only "*.yaml" and that it doesn't work with others. It was not obvious to me, at least until I noticed that the files that my IDE were creating were ".yml" and not "*.yaml". Nevertheless, it is not a big deal. I'm closing the ticket since I believe that this thread can be taken as a side reference.
