### ISSUE TITLE
Move all public API to a service in biz.netcentric.cq.tools.actool.aceservice.api

### ISSUE THREAD

**Issue by ghenzler** [Netcentric/accesscontroltool#157]
For the version 2.0.0, the api should be improved and cleaned up. 

At the moment too many packages are visible. We should create a new service 
biz.netcentric.cq.tools.actool.aceservice.api.AceService with the methods

- `AcInstallationHistory apply()` (instead of execute(), rename `AcInstallationHistoryPojo` to `InstallationLog`)
- `AcInstallationHistory apply(String [] restrictedToPaths)` (instead of execute())
- The additions from #156
- The purgeXXX methods
- For now, the dump methods are to be left out

The JMX interface shall remain mostly unchanged (except that the execute methods should be renamed to `apply`)

Also it looks like biz.netcentric.cq.tools.actool.aceservice.AcInstallService does not have an implementation.

**Comment by kwin** [comment]
Actually `https://github.com/Netcentric/accesscontroltool/blob/develop/accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/aceservice/AcInstallService.java` was the proposed new interface for the AceService. I think it can be taken as a basis.
