### ISSUE TITLE
Error when executing the hook under AEM 6.3

### ISSUE THREAD

**Issue by santiagozky** [Netcentric/accesscontroltool#163]
When executing the installhook under AEM 6.3 the following error happens

`Caused by: javax.jcr.LoginException: Bundle biz.netcentric.cq.tools.accesscontroltool.bundle is NOT whitelisted
	at org.apache.sling.jcr.base.AbstractSlingRepository2.loginAdministrative(AbstractSlingRepository2.java:378)
	at biz.netcentric.cq.tools.actool.dumpservice.impl.DumpserviceImpl.createAclDumpMap(DumpserviceImpl.java:419)`

This seems to be caused by the usage of repository.loginAdministrative. which now is not allowed unless the bundle calling it is explicitly whitelisted  in org.apache.sling.jcr.base.internal.LoginAdminWhitelist

**Comment by kwin** [comment]
There are three solution approaches to this:
1. Whitelist the usage of of the administrative session (https://issues.apache.org/jira/browse/SLING-5135)
2. Use a dedicated service user for this. Not clear how to initially create it with the appropriate rights or whether an existing service user should be just reused.
3. Use the session of the underlying package installation

3. is IMHO the best option for the Vault Install Hook, but not an option for JMX as there is no session/resourceresolver available there. So for JMX we should instead rely on 2.

**Comment by santiagozky** [comment]
I've created a PR with a proporsal for this issue.
https://github.com/Netcentric/accesscontroltool/pull/177
it provides a service user, then it is easy to use loginService instead of loginAdministrative.

**Comment by ghenzler** [comment]
Fixed by #177, after some tests removed cloning of session in 821c4fa6d0a878f81d173f546d618982d7c88a19 to accommodate @kwin's suggestion.
