### ISSUE TITLE
wildcards only for path?

### ISSUE THREAD

**Issue by kleinlain** [Netcentric/accesscontroltool#164]
Hello,

are the wildcards only possible for a full path ('/etc/*/configs', or is it also possible to set a path like '/etc/configs/*-sales-*/mss' to match any kind of /etc/configs/ch-sales-de, /etc/configs/ch-sales-fr... ?

thanks for your help
/anja

**Comment by ghenzler** [comment]
@kleinlain yes it is possible to use wildcards like that. Alternatively you can also use loops as described in [AdvancedFeatures.md#loops](/Netcentric/accesscontroltool/blob/develop/docs/AdvancedFeatures.md#loops)
