### ISSUE TITLE
memberOf property in yaml file is not respected in the first run in version 1.9.4 when using externalId

### ISSUE THREAD

**Issue by luckyluke80** [Netcentric/accesscontroltool#165]
When having two yaml files with group definitions and defining dependencies between these groups with the memberOf declaration and an externalId declaration, the dependency won't be created with the first invocation of the AC Tool.

Steps to reproduce:
1. Create two yaml files
2. add group definition of groupA to fileA and group definition of groupB to fileB
3. add a `memberOf: groupA` declaration to groupB
4. run the AC Tool

Result:
groupA and groupB are created but the dependency from groupB to groupA is missing

Expected:
groupA and groupB are created and the dependency to groupA is also created

If running the AC Tool a second time, the dependency to groupA is created

Versions: Oak: 1.2.21; AC Tool: 1.9.4

Example definition of group A:
`
    - g-admin:
        - name: Master Admin
          path: /home/groups/project/name`

Example definition of group B:

`    - Internal Manager:
        - memberOf: g-admin
          externalId: "cn=<valid_LDAP_Path>`

**Comment by ghenzler** [comment]
Reproduced defect. Only happens if `externalId` is set.
