### ISSUE TITLE
Global config allowExternalGroupNamesRegEx should be renamed as it does not reflect what it means good enough

### ISSUE THREAD

**Issue by ghenzler** [Netcentric/accesscontroltool#171]
While implementing #168 it got apparent that `allowExternalGroupNamesRegEx` is misleading as it is actually possible to use any external groups in `isMemberOf` without setting this. The point of the configuration setting is that the **relationship to/from external groups** will not be cleaned up by the AC Tool if the RegEx matches (normally the AC Tool removes relationships between external groups and config groups that are added manually by design).

I would propose to rename this parameter to `keepExistingMembershipsForGroupNamesRegEx` (initially was here `keepManualRelationshipForGroupNamesRegEx`, changed due to discussion)

**Comment by jochenkoschorke** [comment]
Fine with that. Quite descriptive.

**Comment by kwin** [comment]
I would prefer `keepExistingMembershipsForGroupNamesRegEx`

**Comment by ghenzler** [comment]
Fixed with 9fbae0e65507694097c8c823e6cddcc06947639b. Will fail fast if the old name `allowExternalGroupNamesRegEx` is used.
