### ISSUE TITLE
Configure permissions for anonymous without having to give a password

### ISSUE THREAD

**Issue by poorva-jain** [Netcentric/accesscontroltool#180]
Currently, a user configuration in YAML requires us to provide a password -

- user_config:

  - anonymous:
    - isMemberOf:
      password: secret

Since "anonymous" is a special authorizable, the tool should treat the password as optional. The 'create' and 'move' scenarios for a user should only require passwords. Updating ACL for the user can be handled with password as optional.

**Comment by ghenzler** [comment]
@poorva-jain `anonymous` already exists in AEM installations - you can use `anonymous` in a `members` list without listing it explicitly.

**Comment by poorva-jain** [comment]
@ghenzler Agreed,  "anonymous" can be listed via another group. However, the use-case that I was talking about was 'update/modify permissions of the anonymous user without having to provide the password'. Hope that helps!

**Comment by poorva-jain** [comment]
@ghenzler Let me know if you need more details.

**Comment by mittalkunal** [comment]
Hi @poorva-jain 

If you add anonymous as a part of another group(anonymous_group) then anonymous user will inherit all the permissions provided to anonymous_group. This is how it is implemented in the ACL Tool. Please refer to https://github.com/Netcentric/accesscontroltool/blob/develop/docs/AdvancedFeatures.md#configure-permissions-for-anonymous for more info on the same.

**Comment by kwin** [comment]
Since there is a viable workaround and we don't want to support modifying existing users except for adding them as members to AC managed groups (which is supported without giving the password) I close this issue.
