### ISSUE TITLE
Allow spaces in privileges list

### ISSUE THREAD

**Issue by gruberroland-netcentric** [Netcentric/accesscontroltool#197]
Supported: privileges: jcr:removeChildNodes,jcr:removeNode
Error: privileges: jcr:removeChildNodes, jcr:removeNode

The list of privileges should allow an optional space. This can be easily done with a regex split and would be more user-friendly.

**Comment by ghenzler** [comment]
The properties `actions` (ace_config) and `memberOf` and `members` already support it spaces before and after the commas.
