### ISSUE TITLE
Extend functionality with "purges all ACEs of authorizables contained in configuration files from the system"

### ISSUE THREAD

**Issue by mtstv** [Netcentric/accesscontroltool#20]
I would extend functionality of tool with the next:

AceServiceMBean.java
    @Description("purges all ACEs of authorizables contained in configuration files from the system")
    public String purgeACLsOfAuthorizablesFromConfigurations();

We need to delete only old ACEs of our groups without deletetion of groups, because we don't want to lost the membership for users. 
The number of groups is very large and it's time expensive to collect a list of groups we want do delete. So we don't want to use other existing methods for purging of ACEs. 
After deleting of old ACLs we could just recreate ACEs defined in our new config yaml files.

I extended already the functionality and code is working well already for me.

**Comment by jochenkoschorke** [comment]
Hi,
not sure if i understand your problem correctly but old ACEs regarding groups defined in configurations files which are not covered by a current configuration anymore get automatically deleted with every new execution of the AC Tool (method: execute()). So you don't have to take care about that deletion yourself. Group memberships remain untouched this way (unless you changed that on purpose in a configuration file).

The function purgeACLsOfAuthorizablesFromConfigurations() should only be executed in case you explicitly want to get rid of all groups and their ACE defined in all configuration files which are currently installed.

Is this helpful?

Kind regards,
Jochen

**Comment by mtstv** [comment]
Hi,

I defined an extra group "fragment-test" with read rights for "/" and did execute(). So, the group anmd ACL is there.
After that I deleted this group and ACLs in the yaml file, deployed again and did execute(). The group "fragment-test" and the ACl is still there.

**Comment by mtstv** [comment]
The existing functionality of purgeAllAuthorizablesFromConfigurations() is clear for me.
With new function purge**ACLsOf**AuthorizablesFromConfigurations() I mean that I only want to purge ACLs without deleting of groups. But if you fix the deletion of ACLs of not exiting groups in the yaml config files, the new functionality will be not needed any more.

**Comment by jochenkoschorke** [comment]
Hi, 

"After that I deleted this group and ACLs in the yaml file, deployed again and did execute()"

In order for the automatic purging of old ACEs to work, you must not delete the group from the yaml file, but only the respective ACE definition. The automatic purging during an installation only works for groups which are defined in a yaml file, ACEs of groups not defined in a yaml file remain untouched.

Please also see chapter "Installation Process" in the documentation:

"During the installation all groups defined in the groups section of the configuration file get created in the system. In a next step all ACEs configured in the ACE section get installed in CRX. Any old ACEs regarding these groups not contained anymore in the config but in the repository gets automatically purged thus no old or obsolete ACEs stay in the system and any manual change of ACEs regarding these groups get reverted thus ensuring a defined state again. ACEs not belongig to those groups in the configuration files remain untouched. So after the installation took place all groups and the corresponding ACEs exactly as defined in the configuration(s) are installed on the system"

Kind regards,
Jochen

**Comment by mtstv** [comment]
Hi Jochen,

you suggestion to leave the old not used any more groups without membership and ACLs definition inside of yaml files works well.
But it seems more as workaround how to delete ACEs of old groups.
At least it is better to describe the ACE deletion in the documentation separately.

Thanks and best regards,
Marat

**Comment by mtstv** [comment]
I created a wiki page about how to delete a lot of old groups and their ACEs.

**Comment by mtstv** [comment]
Hi Jochen,

I just identify, that ACE of old groups will be not deleted under the /libs. Is it feature or bug?

Regards,
Marat
