### ISSUE TITLE
Oak Index should not use Oak property index

### ISSUE THREAD

**Issue by joerghoh** [Netcentric/accesscontroltool#219]
The sample index for the rep:ACL nodes should not use an Oak property index, because it will always traverse the complete repository. When using a Lucene index, it's possible to exclude certain parts of the repo from indexing.

And there are quite some areas, which do normally not contain any ACLs, but contain a lot of nodes. For example the complete /jcr:system/jcr:VersionStorage/* could be excluded; this will speedup the index generation (or rebuild :-)) a lot on larger repositories. And of course it's easier then to fine-tune the definition per project level, if it's already a Lucene index.

I don't think that the AC Tool really needs the features of the synchronous Oak property indexes.

**Comment by ghenzler** [comment]
@joerghoh thanks for this suggestion! Could you create a PR for the index definition you have created for your project?

**Comment by kwin** [comment]
Since when do Lucene-based indices in Oak also support property constraints? Remember we have to support back to AEM 6.1. Also path restrictions are supported in Oak property indices (https://issues.apache.org/jira/browse/OAK-3263) since AEM 6.2.

**Comment by kwin** [comment]
> Since when do Lucene-based indices in Oak also support property constraints?
I think this has been introduced with https://issues.apache.org/jira/browse/OAK-2278 so AEM 6.1 should support that.

**Comment by kwin** [comment]
Path restrictions are only supported in Lucene since Oak 1.2.3 (https://issues.apache.org/jira/browse/OAK-2599), so we cannot implement that except we increment the minimum system requirements.

**Comment by joerghoh** [comment]
AFAIK AEM 6.1 is the oldest version you want/need to support. AEM 6.1 SP1 (and there should be already an SP2) comes with Oak 1.2.15 so from my point of view it shouldn't be a problem to require a version newer than 1.2.3

**Comment by Buuhuu** [comment]
FYI: In the deployment scenario described in #298 its quite handy to have a synchronous index. An asynchronous index could cause issues with sling provisioning model based deployments.

**Comment by joerghoh** [comment]
asynchronous indexing is always. a bit uncontrollable, because it runs async. In your case it can block the thread until the index build has been completed, so not causing any issues with the deployment itself. But on the long run I encountered a good number of issues (all not necessarily performance relevant) when you use a property index.

**Comment by ghenzler** [comment]
After all, I think it's best to get rid of the index altogether (it's only needed in one spot). It seems easy enough to replace the query for ACLs with another one - see #386 for details.

**Comment by kwin** [comment]
Meanwhile the indexes are Lucene ones: https://github.com/Netcentric/accesscontroltool/blob/develop/accesscontroltool-oakindex-package/src/main/jcr_root/_oak_index/repACL-custom-1.xml. This was done in the context of #549
