### ISSUE TITLE
Runmodes are not respected when installing via InstallHook 

### ISSUE THREAD

**Issue by joerghoh** [Netcentric/accesscontroltool#223]
I just tracked down an issue where installing a content package containing ACLs failed when the InstallHook as been used.
We define in 2 different (distinct) runmode-based configurations the same group and the duplicate detection fails because of this. I got it working when I removed the "duplicate" definitions.
Following the code paths below the AcToolInstallHookServiceImpl I don't find any reference to the SlingSettingsReference.

We use version 1.9.5  (AEM 6.1) at the moment, but I am open to update a newer version if the issue is fixed there.

**Comment by ghenzler** [comment]
@joerghoh I tried to reproduce the issue but couldn't (neither for 1.9.5 nor for the latest from develop). Could you please try to install the minimal package [actool-runmodetest-1.0.0.zip](https://github.com/Netcentric/accesscontroltool/files/1394367/actool-runmodetest-1.0.0.zip) to see if that works for you? (it uses two simple config file for author/publish that contain the same authorizable)

**Comment by ranjeetsinghy** [comment]
@ghenzler Can you please create 2 folder one with the name "**config.author**" and other one with "**config.author.dev**" and keep the same config file in both of them and then if we try to install authorizables to the author server having "dev" as it's runmode by using the install hook , then hook won't respect the runmodes. It will try to install both the config files, ideally it should only pick the one which is in config.author.dev.

**Comment by ghenzler** [comment]
This behavior is by design: The runmodes found in folder name have to be all active on target AEM instance for the contained config files to become active- for your example this is tru for both folders. 

The way to work with this is to put dev-independent parts into config.author/myconfig.yaml and only dev specific parts into config.author.dev - the tool automatically merges those folders according the runmode.

**Comment by ranjeetsinghy** [comment]
So the behaviour is not exactly same as the runmodes works in OSGI. Because in OSGI, the most matched runmode will be picked up, but in this case, it will pick up "config.author" as well as "config.author.dev".
