### ISSUE TITLE
Expose properties from subnodes of jcr:content during for loop

### ISSUE THREAD

**Issue by josephrignanese** [Netcentric/accesscontroltool#225]
Hi, we have a need to make use of properties from nodes beneath jcr:content during the for loop over a content structure.

Currently, only the direct properties of the jcr:content node are exposed.

What do you think about exposing such properties?

**Comment by ghenzler** [comment]
@josephrignanese my worry is that for some use cases, the structure underneath jcr:content could be very deep... could you explain your actual use case in a bit more detail? (from how many levels down do you actually need to read a property?)

One option could be to introduce a switch in `global_config`,  another one to have an explicit, slightly different FOR syntax...

**Comment by josephrignanese** [comment]
@ghenzler, sure in our case we are looking to go 1 level down from jcr:content since we use the node structure to restrict access to certain properties.

So, imagine the below content structure

- my-page [cq:Page]
  - jcr:contnet [cq:PageContent]
    - restricted-node [nt:unstructured]
      - restricted-property [String]
    - other nodes and properties...

We have access control rules to prevent page editors from modifying anything within the restricted-node since this is configured by our administrators.

But, we want to use the value of restricted-property in our YAML to define some property in the authorizable (in our case it makes up part of the externalId).

**Comment by ghenzler** [comment]
@josephrignanese Ok, I understand. What about using a special syntax for this, e.g. `FOR site IN FULLY LOADED CHILDREN OF /content/myPrj`?

**Comment by josephrignanese** [comment]
Hi @ghenzler, unless you feel strongly about introducing the special syntax I think it would be better to limit the depth of the traversal though a global config.
We could default to 0 which would be equivalent to the current functionality.

**Comment by ghenzler** [comment]
I would prefer to configure on a per loop basis (complex setups might have many loops and most likely deeply loaded children are only used by one) and also, it is even simpler to implement. 

The problem is to come up with a syntax that does not sound silly I guess (I'm not happy with my suggestion from above myself). What about `FOR FULL site IN CHILDREN OF /content/myPrj`?

**Comment by josephrignanese** [comment]
How about 'FOR site WITH CONTENT IN CHILDREN OF /content/myPrj'?

**Comment by ghenzler** [comment]
That sounds good (better than my suggestions ;-) )- if you could update the PR with that (best incl. documentation/junit test) I'll merge and include it in the next release.

**Comment by josephrignanese** [comment]
@ghenzler, I've made the changes on the PR - can you please review and let me know if you have any further suggestions?

**Comment by ghenzler** [comment]
PR looks good. Also tested it and it works like a charm. Thanks for your contribution @josephrignanese!

**Comment by ghenzler** [comment]
Released v2.0.5 with this included.
