### ISSUE TITLE
Cannot set the rootPath property by Access Control Tool

### ISSUE THREAD

**Issue by jacksiu** [Netcentric/accesscontroltool#227]
Hello,

I am migrating the ACL to Accees Control Tool. Currrently, "rootPath" property is set under /home/groups/<group_name>/profile so that the group will have a default search path. 

I have read the document about the Configuration of groups but find no property is for setting "rootpath". I also export the current group setting by groupBasedDump() on JMX interface and find the output has no property about rootpath.

I like the tool very much since it centralizes all ACL into a yaml file. Is there any way to set the rootpath property using Access Control Tool, so that I can also put the group configuration into the file as well? 

![image](https://user-images.githubusercontent.com/22563498/32528507-547f5916-c46e-11e7-824b-c46da2b3953c.png)

**Comment by ghenzler** [comment]
Please have a look https://github.com/Netcentric/accesscontroltool/tree/develop/accesscontroltool-exampleconfig-package Use the OSGi config with PID biz.netcentric.cq.tools.actool.aceservice.impl.AceServiceImpl to configure the place where you put your configuration files in the repository.
