### ISSUE TITLE
Wrong order applied on allow + deny with glob

### ISSUE THREAD

**Issue by henrykuijpers** [Netcentric/accesscontroltool#232]
Config:
    - path: /content
      permission: allow
      actions: read
    - path: /content
      permission: deny
      actions: read, modify, delete
      repGlob: /*

Result:
deny62 (with rep:restrictions sub-node)
allow63
(wrong order)

**Comment by ghenzler** [comment]
@henrykuijpers Please read through https://github.com/Netcentric/accesscontroltool/blob/develop/docs/AdvancedFeatures.md#use-manual-acl-ordering 
Please re-open if that does not work for you.
