### ISSUE TITLE
Executing specific yaml from a group of yaml's for a particular run mode 

### ISSUE THREAD

**Issue by mfaizan313** [Netcentric/accesscontroltool#233]
I have 3 yaml files defined for author run mode. 
My requirement is to execute only one of them using a curl command.
How we can execute using ACTool?

Details:
Version: 1.9.6

**Comment by kwin** [comment]
Please rather use the install hook, which supports run modes out of the box (https://github.com/Netcentric/accesscontroltool/blob/develop/docs/ApplyConfig.md#installation-hook)

**Comment by mfaizan313** [comment]
Hi Kwin

Run modes arn't a problem for me. 
As mentioned in description above I have 3 yaml files defined for author run mode which actool and install hook are addressing. My requirement is to execute only one of them in author run mode which is not happening with neither actool nor install hook even though I exclude some yaml files in filter.xml they are taken into account by install hook.

Please let me know if there is a way to address this.

**Comment by kwin** [comment]
Run modes are the only way of restricting the execution of YAML files to only a subset. You may want to introduce additional run modes to achieve what you are aiming for.

**Comment by mtstv** [comment]
@mfaizan313 Can you provide the full JCR paths to your YAML configs?

**Comment by mfaizan313** [comment]
@mtstv Here you go

/apps/***/***/actool/***.author

**Comment by mtstv** [comment]
@mfaizan313 
Try to use different runmodes for author instances instead of common "author" runmode
/apps/***/***/actool/***.author1/config.yaml
/apps/***/***/actool/***.author2/config.yaml
/apps/***/***/actool/***.author3/config.yaml
