### ISSUE TITLE
colon in group id

### ISSUE THREAD

**Issue by Pekket** [Netcentric/accesscontroltool#234]
We need to create group ids using colons like TEST-AUTHOR:123455
As provided by the customers IDP.

We get an error 

> validation error while reading group data: invalid group name:  TEST-AUTHOR:123455

**Comment by kwin** [comment]
The related PR is at #235.

**Comment by kwin** [comment]
I think the whole validation of authorizable IDs is wrong. At least Oaks UserManager does allow any character as authorizable id (compare with https://github.com/apache/jackrabbit-oak/blob/7999b5cbce87295b502ea4d1622e729f5b96701d/oak-core/src/main/java/org/apache/jackrabbit/oak/security/user/UserManagerImpl.java#L421). So I would rather be in favour of completely removing the validation. As long as this ends up only in a String JCR property there are no restrictions!
