### ISSUE TITLE
Improve/clarify group membership handling for groups managed via AcTool in a multi-tenant setup

### ISSUE THREAD

**Issue by kwin** [Netcentric/accesscontroltool#236]
Consider the following use case:

1. AEM is executed in a multi-tenancy setup
2. The global-configuration is containing some ACL fragments and groups
3. The tenant-specific configuration is containing some other groups (not overlapping) and wants to leverage the same fragments from 2, therefore the tenant specific group extends(!) the global group (i.e. the tenant's group id is added to the global group's member attribute)
4. The global and tenant-specific YAML files are processed in individual packages and installed via the hook
5. With the installation of 2) the groups being set up by 3) are destroyed due to the handling described in https://github.com/Netcentric/accesscontroltool/blob/develop/docs/AdvancedFeatures.md

One workaround would be to exclude the tenant specific-groups in the global configuration. That feels weird as the global configuration should not care about the group names of the tenant specific configuration.

Also I don't get the reasoning for this behaviour 

> This behaviour makes sense to ensure the configuration to be self-contained and prevent unwanted "injection" of permissions into the configuration system as described by the yaml files. Therefore wherever possible groups and their dependent groups should be added to the AC Tool configuration.
 (from https://github.com/Netcentric/accesscontroltool/blob/develop/docs/AdvancedFeatures.md).

IMHO the group membership of package 3 within group from package 2 should not be touched when installing package 2 (i.e. package 2 group members property pointing to package 3 group should not be removed).
If the tenant-specific group is extending another group (means it is member of the other group) being maintained through the ACTool there is no unwanted injection of permission taking place!

So in general: the member property of the ACTool managed group should not be touched (except for values pointing to ACTool managed groups itself). Instead only other group's members should be touched, so that prior to installation the AC managed group is no longer member of any other group!

**Comment by kwin** [comment]
For me only group should be touched which are managed by the ACTool and whose memberships are manually extended! But not vice-versa.

**Comment by ghenzler** [comment]
The code that allows to even use members that are outside of the "configuration space" was added in #168. #212 is another issue going in a similar direction. Writing up https://github.com/Netcentric/accesscontroltool/wiki/Options-for-%22unmanaging%22-certain-aspects-of-configuration in the attempt to clarify things and identify a reasonable way forward.

**Comment by kwin** [comment]
I agree with all use cases from #168 and actually that feature is nice (in fact we are leveraging it). It is only the cleanup I do not agree with.

The only thing we can and should cleanup is the members which point to AC managed groups (i.e. groups from which the ACTool managed group is inheriting). 
Cleaning up members of the ACTool managed group itself (which means touching groups not being managed by ACTool) in general is not a good idea. 

We should have a clear warning in the ACTool when we try to modify through YAML files any group members in a way that they point to non-managed groups (as in this case we cannot do any cleanup!). This must always be an append-only operation!

That said, I think I may have been removed too many things in my PR. Let me rework that again.

**Comment by ghenzler** [comment]
PR #245 implements the deprecation of `keepExistingMembershipsForGroupNamesRegEx` in favor of `defaultUnmanagedExternalIsMemberOfRegex` and `defaultUnmanagedExternalMembersRegex` as described in https://github.com/Netcentric/accesscontroltool/wiki/Options-for-%22unmanaging%22-certain-aspects-of-configuration (but #244 is created to fully implement that, including the failure for the case relationships declared as unmanaged are still included in config)
