### ISSUE TITLE
Upgrade dependencies to AEM 6.1

### ISSUE THREAD

**Issue by kwin** [Netcentric/accesscontroltool#240]
Although with the ACTool 2.0.0 the minimum requirement was adjusted to AEM 6.1 most of the managed dependencies are a much older version. The depMgmt in the reactor pom should be upgraded to the versions shipped with AEM 6.1 (e.g. OSGi R5, which allows to use generics). Unfortunately we cannot yet rely on the UberJar as only since AEM 6.2 the unobfuscated UberJar is publically available from Adobe's Maven repo.

**Comment by ghenzler** [comment]
Reverted this as there was compilation errors e8ce2f91a10

**Comment by kwin** [comment]
Yeah, it seems a lot of dependencies from AEM 6.1 are not available in the Adobe Maven Repo. Unfortunately we cannot yet leverage the uber-jar as well (as the unobfuscated version is only available publically for AEM 6.2 and above). Is it ok to move the minimum requirements to AEM 6.2 these days?

**Comment by kwin** [comment]
Fixed via merging https://github.com/Netcentric/accesscontroltool/pull/273.
