### ISSUE TITLE
AC Tool from develop branch is not compatible with AEM 6.1

### ISSUE THREAD

**Issue by otarsko** [Netcentric/accesscontroltool#254]
It's written in Requirement that AC Tool compatible with AEM 6.1, but one package cannot be wired:

From bundle `biz.netcentric.cq.tools.accesscontroltool.bundle`:
`org.apache.jackrabbit.oak.spi.security.principal,version=[1.1,2) -- Cannot be resolved`

But bundle `org.apache.jackrabbit.oak-core` exports only `org.apache.jackrabbit.oak.spi.security.principal,version=1.0.0`

With SP1 bundle starts and AC Tool works.

**Comment by ghenzler** [comment]
Fixed in documentation (as everyone running AEM 6.1 today should really have installed SP1 at least)
