### ISSUE TITLE
Exception while applying example configuration

### ISSUE THREAD

**Issue by otarsko** [Netcentric/accesscontroltool#255]
After trying to apply test configuration `/apps/netcentric/actool-exampleconfig/realProject` I received next exception:
> 
> 20:10:53.775:  *** Applying AC Tool Configuration using v2.0.4.SNAPSHOT... 
> 20:10:53.816:  Found configuration file /apps/netcentric/actool-exampleconfig/realProject/system.author/config.yaml
> 20:10:53.983:  Found configuration file /apps/netcentric/actool-exampleconfig/realProject/serviceuser.author/config.yaml
> 20:10:53.988:  Found configuration file /apps/netcentric/actool-exampleconfig/realProject/global.author/config.yaml
> 20:10:54.043:  Loaded configuration in 262ms
> 20:10:54.043:  Starting installation of merged configurations...
> 20:10:54.413:  Retrieved existing ACLs from repository in 370ms
> 20:10:54.413:  *** Starting installation of 24 authorizables...
> 20:10:54.548:  Found change of intermediate path for system-tags: /home/groups/s -> /home/users/system/s
> 20:10:54.549: EXCEPTION: biz.netcentric.cq.tools.actool.authorizableinstaller.AuthorizableCreatorException: biz.netcentric.cq.tools.actool.authorizableinstaller.AuthorizableCreatorException: Cannot add authorizable system-tags as member of itself.

AEM 6.1 SP1

**Comment by ghenzler** [comment]
The example is wrong, group and user in https://github.com/Netcentric/accesscontroltool/blob/ff5916ba30fbba7ad8422ff544665132dd33ec7b/accesscontroltool-exampleconfig-package/src/main/jcr_root/apps/netcentric/actool-exampleconfig/realProject/serviceuser.author/config.yaml should be named differently.

**Comment by otarsko** [comment]
@ghenzler would it be fine to add "-group"  to groups name?

**Comment by ghenzler** [comment]
I would rather change the user names to system-user-xxx (and potentially take out the groups altogether, the are often not reusable for the system user use case an the do not make much sense). Also the path should be removed or named differently, the value 's' usually means this was exported and then adapted for this example, for tailored definitions it's better to use a speaking name.

**Comment by ghenzler** [comment]
Thanks @otarsko!
