### ISSUE TITLE
Allow to reuse variables from other YAML files

### ISSUE THREAD

**Issue by kwin** [Netcentric/accesscontroltool#257]
Currently the functional logic (loops, variables, ...) only work on a per YAML-file basis. It is not possible to declare variables once in one YAML file and use it then in multiple others. This is often desirable though for more complex setups.

Currently the code in https://github.com/Netcentric/accesscontroltool/blob/65f4dfd962a525a0ac1ea2e5f4433f07c5a5eed6/accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/configreader/YamlMacroProcessorImpl.java#L59 leads to the fact that for each YAML file the variables map is being empty.

In addition one would need to clarify the order in which YAML files are processed (depth first vs. breadth first or all in alphabetical order).

**Comment by otarsko** [comment]
How about importing other yaml files introducing new configuration section "import_config"? E.g.:

```
- import_config:

  - imports:
      groupNames: groupNames.yaml
      userNames: ../folderA/userNames.yaml
```

On evaluation, we export variables definitions into the parent scope (so the yaml file these imports are defined in), and then make them accessible as `${userNames.userA}`.

It looks like a big change though.

**Comment by ghenzler** [comment]
@otarsko So I tried a few things back and forth - the issue with importing a yaml file is that normally all yaml files are taken into account (so you would import it and you would have to exclude it from "normal operations"). Please have a look at https://github.com/Netcentric/accesscontroltool/blob/cf858eec512f01dc408e993647b7d575f297ad47/docs/AdvancedFeatures.md#global-variables if that works for you - together with the multiline syntax of https://github.com/Netcentric/accesscontroltool/blob/cf858eec512f01dc408e993647b7d575f297ad47/docs/AdvancedFeatures.md#variables this should really allow for anything that is needed
