### ISSUE TITLE
Logging suppressed on errors and can we use the other jstl functions

### ISSUE THREAD

**Issue by dchilkur** [Netcentric/accesscontroltool#260]
Just started exploring the ACL tool locally, thank you the great work

Two things I needed some help with:
1.  **Seeing some log entries being suppressed( not reported), other than the NPE being reported - installing the ACL's via package - especially from the line below**

```
            installLog.addError(e.toString()); // ensure exception is added to installLog before it's persisted in log in finally clause
            throw e; // handling is different depending on JMX or install hook case
```
```
02.02.2018 19:58:06.670 *DEBUG* [qtp277129822-288-ACTool-Config-Worker] biz.netcentric.cq.tools.actool.configreader.YamlMacroChildNodeObjectsProviderImpl Loop for children of /content/www evaluates to 31 children
02.02.2018 20:01:36.963 *DEBUG* [qtp277129822-288-ACTool-Config-Worker] biz.netcentric.cq.tools.actool.history.impl.HistoryUtils create node: history_1517601696963_via_acltool-1.0
02.02.2018 20:01:36.984 *DEBUG* [qtp277129822-288-ACTool-Config-Worker] biz.netcentric.cq.tools.actool.history.impl.HistoryUtils delete obsolete history node: 
02.02.2018 20:01:36.985 *INFO* [qtp277129822-288-ACTool-Config-Worker] biz.netcentric.cq.tools.actool.history.impl.HistoryUtils Saved history in node: /var/statistics/achistory/history_1517601696963_via_acltool-1.0
02.02.2018 20:01:36.990 *DEBUG* [qtp277129822-288-ACTool-Config-Worker] biz.netcentric.cq.tools.actool.history.impl.AcHistoryServiceImpl Saved installed configuration files under : /var/statistics/achistory/history_1517601696963_via_acltool-1.0/installedConfigs
02.02.2018 20:01:37.123 *ERROR* [qtp277129822-288] biz.netcentric.cq.tools.actool.installhook.AcToolInstallHook Exception during execution of install hook: java.lang.NullPointerException
java.lang.NullPointerException: null
	at com.day.crx.packaging.impl.response.StreamedScriptResponse.onError(StreamedScriptResponse.java:131)
	at com.day.jcr.vault.fs.impl.JrVltProgressTrackerListener.onError(JrVltProgressTrackerListener.java:50)
	at biz.netcentric.cq.tools.actool.history.ProgressTrackerListenerInstallationLogger.addError(ProgressTrackerListenerInstallationLogger.java:29)
	at biz.netcentric.cq.tools.actool.impl.AcInstallationServiceImpl.installConfigurationFiles(AcInstallationServiceImpl.java:218)
	at biz.netcentric.cq.tools.actool.installhook.impl.AcToolInstallHookServiceImpl.installYamlFilesFromPackage(AcToolInstallHookServiceImpl.java:44)

```

**2. how can we use other functions like length etc. wanted to do something like this** 

`- IF ${lname.length == "5"}:`

**Comment by ghenzler** [comment]
Great to hear that you like the tool @dchilkur. Regarding you questions:

1. The code you mention is just some tweaks for the end of the log if there is an error. Generally errors during execution should make it into the log file **and** the package installation log (was this not the case for the NPE you had?)
2. Additional methods could be added here: https://github.com/Netcentric/accesscontroltool/blob/develop/accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/configreader/YamlMacroElEvaluator.java#L97 - but I think your example would have to be  `${length(lname) == 5}`. What additional methods would you like to see?

**Comment by ghenzler** [comment]
@dchilkur How dynamic is your list of countries? Probably the easiest to work with a list of fixed values `FOR locale IN [ca, ...]`....

**Comment by SaurabhPatel005** [comment]
@ghenzler: Now adding on behalf of @dchilkur. As mentioned above, we are in need to add a method which checks the length of the string. 
we tested adding method locally and its working as expected. 
do we need to create a PR? if yes, it seems like we don't have enough privileges. Let me how we can add "length" method in this repo. 
Thanks

**Comment by kwin** [comment]
Regarding issue 1.: I can reproduce and try to fix. The basic issue why this NPE occurs is that the exception seems to be null and it is dereferenced via {{toString}} in {{com.day.crx.packaging.impl.response.StreamedScriptResponse.onError(StreamedScriptResponse.java:132)}}
