### ISSUE TITLE
Allow empty configuration files 

### ISSUE THREAD

**Issue by ghenzler** [Netcentric/accesscontroltool#261]
Sometimes it would be good to allow empty configuration files that only contain a comment (e.g. we had a file `obsolete-authorizables.yaml` that I wanted to leave with a comment (so it could be used to add new obsolete authorizables at some point), but currently this leads to an error

**Comment by mtstv** [comment]
This helps

`
# OLD GROUPS TO DELETE ACEs FOR

# definition must be there to avoid NullPointerException
- group_config:
`
