### ISSUE TITLE
Support clearing authorizable properties

### ISSUE THREAD

**Issue by kwin** [Netcentric/accesscontroltool#268]
Currently all properties being set on authorizables (groups or users) are optional and only in case they are not empty in the YAML the according property gets set on existing/new authorizables. 

In fact we should also clean those properties from existing groups/users if a YAML files is installed which manages those users/groups but does not set those properties.

I.e. removing a `description` property from a group definition currently does not lead to the removal of the description property in the repo (if the group exists already) but actually if should.

Of course only properties should be touched which are explicitly supported in our YAML, so I am talking only about the following JCR properties here

1. `profile/givenName` for group and user
1. `profile/aboutMe`
1. `profile/familyName` (only for user)

**Comment by ghenzler** [comment]
@kwin this sound good to me
