### ISSUE TITLE
Check return value of Group.addMember and Group.removeMember and log error accordingly

### ISSUE THREAD

**Issue by kwin** [Netcentric/accesscontroltool#275]
Currently a failure to add an authorizable as member to an existing group is not properly checked in code. The return value of https://github.com/Netcentric/accesscontroltool/blob/5dd1e91f668457d111f87780362ce49d8b36a3bc/accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/authorizableinstaller/impl/AuthorizableInstallerServiceImpl.java#L184 and https://github.com/Netcentric/accesscontroltool/blob/5dd1e91f668457d111f87780362ce49d8b36a3bc/accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/authorizableinstaller/impl/AuthorizableInstallerServiceImpl.java#L196 must be properly checked for the return value `true`. Otherwise at least a warning should be issued. 

This is especially useful if someone is trying to add members to group "everyone" which is not supported (compare with https://issues.apache.org/jira/browse/OAK-7323).

**Comment by ghenzler** [comment]
After fixing #285 the branch https://github.com/Netcentric/accesscontroltool/compare/feature/275-check-for-return-values-of-addMember-and-removeMember still produces warnings for a roundtrip of `purgeAllAuthorizablesFromConfiguration()` and `apply()`, it looks like if for the case a group is deleted itself, changes to it are not persisted on save() anymore and hence if "resurrected" via `apply()`, some memberships already exist.
