### ISSUE TITLE
New user with encrypted password is created but login into AEM fails

### ISSUE THREAD

**Issue by andreibuboi** [Netcentric/accesscontroltool#288]
I tried to create a user according to the documentation but I can't login with the created user into AEM. 
I used /system/console/crypto to get encrypted password and copied that into the configuration file with braces and double quotes. The user appears in the administrator user interface. AEM version is 6.3

**Comment by kwin** [comment]
Which version of the ACTool are you using?

**Comment by andreibuboi** [comment]
ACTool version 2.0.2

**Comment by kwin** [comment]
This feature has been added with 2.0.4 (https://github.com/Netcentric/accesscontroltool/issues/251). Please upgrade.

**Comment by andreibuboi** [comment]
thank you for the help
