### ISSUE TITLE
ACTool hook documentation is not updated for content-package-maven-plugin:1.0.2

### ISSUE THREAD

**Issue by carlosmorenoin** [Netcentric/accesscontroltool#295]
Starting with the 1.0.2 release of Adobe’s content-package-maven-plugin, all the content packaging functionality was removed, so the plugin can be used together with filevault-package-maven-plugin in the same project. As the Hook gets executed on the packaging phase projects with the new version of the content-package-maven-plugin have to apply the configuration under the filevault-package-maven-plugin.

Please update the documentation https://github.com/Netcentric/accesscontroltool/blob/develop/docs/ApplyConfig.md to reflect this change.

**Comment by kwin** [comment]
@carlosmorenoin Thanks for the PR. It is merged now.
