### ISSUE TITLE
Add ArrayUtils#contains to imported functions

### ISSUE THREAD

**Issue by luckslovez** [Netcentric/accesscontroltool#311]
It would be great to use https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/ArrayUtils.html#contains-java.lang.Object:A-java.lang.Object- as the rest of imported functions. That would allow for something like
` DEF strings=[hey,ho]`
 `- FOR item IN CHILDREN OF /my/repo:`
 `     - IF ${strings.contains(item.name)}:`

Thanks!

**Comment by ghenzler** [comment]
Changed syntax to containsItem(RUNMODE, 'runmode') @kwin's comment #321 (comment)

**Comment by ghenzler** [comment]
Fixed in v2.2.0
