### ISSUE TITLE
Allow to have conditions for run modes

### ISSUE THREAD

**Issue by kwin** [Netcentric/accesscontroltool#312]
Run modes are often used to distinguish between different aspects of a instance. It is very common to have a run mode per environment (i.e. for DEV/STAGE/PROD). In the case of SSO with the same backend you often want to use different group names for those instances (as otherwise a user having certain rights on a DEV instance automatically has the same rights on PROD). Instead of using runmode specific YAML files it would be handy if you could reference run modes within conditions within the YAML file. That way less code duplication is necessary.

**Comment by kwin** [comment]
This would go nicely along with #311.

**Comment by ghenzler** [comment]
With 022eaeb the syntax would be `containsElement(RUNMODE, 'runmode')` - or should we have a custom syntax for this?

**Comment by ghenzler** [comment]
Changed syntax to `containsItem(RUNMODES, 'runmode')` @kwin's comment https://github.com/Netcentric/accesscontroltool/pull/321#discussion_r224343924

Added unit test to show that `- FOR runmode IN ${RUNMODES}: ` works correctly.
