### ISSUE TITLE
Issue publishing Assets on Brand Portal.

### ISSUE THREAD

**Issue by rairahul89** [Netcentric/accesscontroltool#319]
When a node is given read and replicate permission we are not able to publish content on Brand Portal but able to publish on AEM publish instance. While we elevate the permissions to read, create, modify and replicate then it is publishing content on Brand Portal.

**Comment by ghenzler** [comment]
@rairahul89  Your issue sounds more like a general setup issue. What do the permissions look like in CRXDE of the node you cannot publish? Is "Brand Portal" an AEM Author instance?

**Comment by rairahul89** [comment]
AEM Assets Brand Portal is an Adobe provided SaSS service that facilitates the secure, scalable and controlled distribution of approved brand assets via an internet facing web property. 
AEM Assets is used in conjunction with AEM Author 6.2 or greater, which publishes the approved assets to Brand Portal.Brand Portal users are managed via the Adobe Cloud, and are not AEM users, nor are they managed in AEM Author itself.
@ghenzler : Yes you are right, as it was confirmed from adobe that publishing a content to Brand Portal can be achieved only by authors who have read, create, modify and replicate permissions. So for now users who have only read and replicate permissions then they won't be able to publish to Brand Portal.
