### ISSUE TITLE
Yaml tenant file overwritten other tenant permissions on AEM 6.4

### ISSUE THREAD

**Issue by calewelt** [Netcentric/accesscontroltool#339]
Hello all,
we have some problems with our permissions after migration from AEM 6.2 to AEM 6.4
We run our tenant file for differnt solution. Normally one by one. At the moment we have the issue when we run only one tenant with the file the other permission on the first level are overwritten.When we run all tenants with one file than it looks good. But we could not run all tenants together every tim because we have differnt requirements.
Have one of you an idear how we could resolve it ?

An extract from our tenant yaml file:

  - group_config:

      - FOR tenant IN [ XXXX]:

        # tenant final roles

        - ${tenant}_lighteditor:
          - name:
            memberOf: ddp_role_fragment_lighteditor, ${tenant}_sites_fragment_read, ${tenant}_dam_fragment_read, ${tenant}_tags_fragment_read, ${tenant}_design_projects_fragment_read,${tenant}_conf_fragment_read
            path: /home/groups/ddpsites/${tenant}
            isGroup: 'true'

        - ${tenant}_normaleditor:
          - name:
            memberOf: ddp_role_fragment_normaleditor, ${tenant}_sites_fragment_read, ${tenant}_dam_fragment_read, ${tenant}_tags_fragment_read,${tenant}_conf_fragment_read,${tenant}_conf_fragment_replicate, ${tenant}_sites_fragment_create_modify, ${tenant}_dam_fragment_create_modify, ${tenant}_dam_fragment_delete, ${tenant}_dam_fragment_replicate, ${tenant}_tags_fragment_create_modify, ${tenant}_campaigns_fragment_read, ${tenant}_design_projects_fragment_read
            path: /home/groups/ddpsites/${tenant}
            isGroup: 'true'

        - ${tenant}_chiefeditor:
          - name:
            memberOf: ddp_role_fragment_chiefeditor, ${tenant}_sites_fragment_read, ${tenant}_dam_fragment_read, ${tenant}_tags_fragment_read, ${tenant}_sites_fragment_create_modify, ${tenant}_sites_fragment_delete, ${tenant}_sites_fragment_replicate,${tenant}_conf_fragment_read, ${tenant}_dam_fragment_create_modify, ${tenant}_dam_fragment_delete, ${tenant}_dam_fragment_replicate, ${tenant}_tags_fragment_create_modify, ${tenant}_campaigns_fragment_read, ${tenant}_tags_fragment_delete, ${tenant}_tags_fragment_replicate, ${tenant}_reports_fragment_read, ${tenant}_reports_fragment_read, ${tenant}_campaigns_fragment_create_modify, ${tenant}_campaigns_fragment_delete, ${tenant}_campaigns_fragment_replicate, ${tenant}_design_projects_fragment_read, ${tenant}_design_projects_fragment_create_modify, ${tenant}_design_projects_fragment_delete, ${tenant}_design_projects_fragment_replicate
            path: /home/groups/ddpsites/${tenant}
            isGroup: 'true'

        - ${tenant}_siteadmin:
          - name:
            memberOf: ddp_role_fragment_siteadmin, ${tenant}_sites_fragment_all, ${tenant}_dam_fragment_all, ${tenant}_tags_fragment_all, ${tenant}_reports_fragment_all, ${tenant}_campaigns_fragment_all,${tenant}_conf_fragment_all ,${tenant}_packages_fragment_all, ${tenant}_designs_fragment_all, ${tenant}_design_projects_fragment_all
            path: /home/groups/ddpsites/${tenant}
            isGroup: 'true'

Here are an example of 1 other group where the permissions are overwritten:

![image](https://user-images.githubusercontent.com/45826048/49881897-afbb3600-fe2f-11e8-919b-dda4069e9d04.png)

**Comment by calewelt** [comment]
Hello all,
i found the issue by my own.
The yaml script started with a clean up prozedure and removed all external member from my overall group

For example:
Removing 1 external members to group ddp_role_fragment_lighteditor
16:02:07.925:  Removing eon-sales-ro_lighteditor as external member to group ddp_role_fragment_lighteditor

It is possible to start the script without clean ups ?

**Comment by ghenzler** [comment]
@calewelt One of the most important features of the AC tool is that it always creates a delta: it will always check what is there, compare it to what should be there (as found in config) and then add/delete accordingly. Having said that, you have full control on what exactly is happening by configuring unmanaged aspects:
https://github.com/Netcentric/accesscontroltool/blob/develop/docs/AdvancedFeatures.md#configure-unmanaged-aspects
