### ISSUE TITLE
ACTool for Sling standalone application

### ISSUE THREAD

**Issue by andreeacoman2507** [Netcentric/accesscontroltool#348]
We are building a Sling 11 standalone application and would like to be able to use ACTool. Currently, ACTool only works with AEM projects. We installed accesscontroltool-package 2.2.0, and the package appears in 'Installed' state, with the following unresolved dependencies:
* com.adobe.granite.crypto,version=[1.4,2)
* com.adobe.granite.jmx.annotation,version=[1.0,2)
* com.day.cq.security.util
* org.apache.jackrabbit.oak.spi.security.authentication.external,version=[1.0,3)
* org.apache.jackrabbit.oak.spi.security.authentication.external.basic,version=[1.0,2)

We are not sure whether the last two dependencies are AEM related.
Would it be possible to obtain an ACTool build with no AEM dependencies? Thank you for your support.

**Comment by kwin** [comment]
The latter two should be made optional. They are only required in case someone leverages an LDAP integration.
It will be tricky though to get rid of the 3rd one as that package contains the CqActions (https://helpx.adobe.com/experience-manager/6-2/sites/developing/using/reference-materials/javadoc/com/day/cq/security/util/CqActions.html)
