### ISSUE TITLE
privileges vs actions: which one to use?

### ISSUE THREAD

**Issue by ghost** [Netcentric/accesscontroltool#356]
Are there pros/cons of one over the other? The only thing I can think of is that privileges can be more granular compared to actions.

But if I want is giving some RWED permission to a node (examples: /etc/workflows or /var/workflows or /content/mysite/en), seems actions can easily do this?

Thanks

**Comment by ghenzler** [comment]
Actions are a pure AEM concept - they are higher level (e.g. for pages it results in privileges for the `jcr:content` node and the page node itself)

Privileges are a pure JCR concept (lower level) - if you run Sling only you can only use these. 

In general I would recommend to use actions when using AEM and pages, for non `/content` nodes I would go more with privileges. But in the end you can mix and match as needed.
