### ISSUE TITLE
how to give access to a path without giving access to any of the stuff inside it?

### ISSUE THREAD

**Issue by ghost** [Netcentric/accesscontroltool#367]
I have this path/folder structures

/content/mysite/en/products/electrical
/content/mysite/en/products/home

I want to give read/write access to just the products folder without giving access to eletrical and home.

How can do I do this? Thank you

**Comment by ghenzler** [comment]
See https://github.com/Netcentric/accesscontroltool/blob/develop/docs/BestPractices.md#white-listing-nodes
