### ISSUE TITLE
Ac Tool only set modify, create, delete actions in repository

### ISSUE THREAD

**Issue by jochenkoschorke** [Netcentric/accesscontroltool#37]
Since 1.6.1 release, the AC Tool only sets modify, create, delete cq-actions in repository. Other cq-actions like read doesn't get set anymore.

**Comment by kwin** [comment]
The fix should take care that additional restrictions are correctly applied on the privileges set through actions, because in quite some projects there is rep:glob used together with CQ actions (which is not supported by the CqActions API).
