### ISSUE TITLE
Fix tag paths in examples to use `/content/cq:tags` 

### ISSUE THREAD

**Issue by ghenzler** [Netcentric/accesscontroltool#375]
Fix tag paths in examples to use `/content/cq:tags` instead of old `/etc/tags`

e.g. https://github.com/Netcentric/accesscontroltool/blob/develop/accesscontroltool-exampleconfig-package/src/main/jcr_root/apps/netcentric/actool-exampleconfig/realProject/global.author/config.yaml#L37

**Comment by gayathrigs27** [comment]
raised a pr for it
