### ISSUE TITLE
actool verbose log level

### ISSUE THREAD

**Issue by sparktronics** [Netcentric/accesscontroltool#385]
I have noticed that with the new releases of the actool it is so smooth that when it executes and creates new users (only modified ones), it does not logs anything to the screen.  Since it does not logs anything to the screen, it appears like it has not been executed at all.

Would it make sense to always log a message? of course, when you add -X the message will appear but not by default.

**Comment by ghenzler** [comment]
So `-X` looks like you are using maven with a package that uses the AC Tool - for this use case you can use `-Dvault.verbose` to make the `content-package-maven-plugin` log the install hook messages. Regarding the log for creating new users, I tested:

```
*** Starting installation of 141 authorizables... 
Finished installation of authorizables without errors in 298ms 
```
this created one user (when all the users existed)... there should be at least one summary message in regular log and one message per user created as verbose message

**Comment by sparktronics** [comment]
thanks! problem solved
