### ISSUE TITLE
Support principal based authentication

### ISSUE THREAD

**Issue by ghenzler** [Netcentric/accesscontroltool#396]
When using the service authentication, principals can be used directly instead of system users: https://sling.apache.org/documentation/the-sling-engine/service-authentication.html#service-user-mappings / https://issues.apache.org/jira/browse/SLING-6963

**Comment by kwin** [comment]
What does it have to do with the ACTool? The configuration for Sling service users is not maintained by ACTool (and IMHO shouldn't be). You can already use it now by
a) Manually providing an OSGi config for the service authentication based on principals (look at https://sling.apache.org/documentation/the-sling-engine/service-authentication.html#service-user-mappings for details)
b) Create groups/fragments with that principal ID with the ACTool

Currently there is no principals in AEM which are not being backed by Authorizables (i.e. Oak Users or Groups)

Update: There was a question about that raised in https://lists.apache.org/thread.html/84f683c08b7f0dabf1dc06168175c3da93da4a3945416cbbcff396d9@%3Cdev.sling.apache.org%3E

**Comment by kwin** [comment]
I think the only relevant change is tracked already in #369.

**Comment by kwin** [comment]
Actually this is not true. To directly maintain principal privileges a `PrincipalAccessControlList` structure is used (https://jackrabbit.apache.org/oak/docs/security/authorization/principalbased.html). That allows to set privileges for
1. users not imported into AEM
2. paths not yet existing

Also compare with https://github.com/Adobe-Consulting-Services/acs-aem-commons/issues/2541.

**Comment by kwin** [comment]
AEMaaCS supports principal based authorization by default only for all users below `/home/users/system/cq:services`

**Comment by kwin** [comment]
Closing as only #369 is missing.
