### ISSUE TITLE
Question: unable to deny access to a specific workflow

### ISSUE THREAD

**Issue by mickleroy** [Netcentric/accesscontroltool#397]
Hi,

I'm following your suggested fragment organisation (global, content and functional) and it's been working beautifully so far.

However, I've been approached to deny access to the deactivation workflow for a particular group and I'm running into issues applying the new rule.

I'm using a configuration like this:
```
# existing fragment
- fragment-workflows:
       - path: /var/workflow
          permission: allow
          actions: read,modify,create,delete,acl_read,replicate
          privileges:
          repGlob:

# new fragment to deny access (not working)
 - fragment-deny-deactivate:
       - path: /var/workflow/models/request_for_deactivation
          permission: deny
          actions: read,modify,create,delete,acl_read,replicate
          privileges:
          repGlob:
```
When this configuration is applied, the following stack trace is thrown:
```
*INFO* [qtp1315343726-5558-ACTool-Config-Worker] biz.netcentric.cq.tools.actool.aceinstaller.BaseAceBeanInstaller *** Finished installation of 178 ACLs in 186ms
*INFO* [qtp1315343726-5558-ACTool-Config-Worker] biz.netcentric.cq.tools.actool.history.impl.HistoryUtils Saved history in node: /var/statistics/achistory/history_1574894245034_via_acls-config
*ERROR* [qtp1315343726-5558] biz.netcentric.cq.tools.actool.installhook.AcToolInstallHook Exception during execution of install hook: javax.jcr.version.VersionException: OakVersion0001: Cannot add property jcr:mixinTypes on checked in node
javax.jcr.version.VersionException: OakVersion0001: Cannot add property jcr:mixinTypes on checked in node
	at org.apache.jackrabbit.oak.api.CommitFailedException.asRepositoryException(CommitFailedException.java:242)
	at org.apache.jackrabbit.oak.api.CommitFailedException.asRepositoryException(CommitFailedException.java:213)
	at org.apache.jackrabbit.oak.jcr.delegate.SessionDelegate.newRepositoryException(SessionDelegate.java:669)
	at org.apache.jackrabbit.oak.jcr.delegate.SessionDelegate.save(SessionDelegate.java:495)
	at org.apache.jackrabbit.oak.jcr.session.SessionImpl$8.performVoid(SessionImpl.java:420)
	at org.apache.jackrabbit.oak.jcr.delegate.SessionDelegate.performVoid(SessionDelegate.java:273)
```

Any ideas what could be causing this?

**Comment by ghenzler** [comment]
@mickleroy You can also try in CRXDE and you'll get the also an error (and the exact same `VersionException` in the `error.log`). As workaround you can move one (or multiple)  workflow models in a folder and set permissions on that folder

**Comment by ghenzler** [comment]
@mickleroy Please re-open if you have an idea on how to improve the situation in the AC Tool, but as noted above the root cause is the repo setup itself not supporting this.

**Comment by henrykuijpers** [comment]
@ghenzler Maybe this can be reopened, since we now also have principal based ACL? https://jackrabbit.apache.org/oak/docs/security/authorization/principalbased.html

This way, we could configure the principal with the effective path of the workflow model? 

`all entries will grant access (i.e. no deny)`

This does imply that a simple deny is not possible, though. I.e. one would have to create a deny using the normal ACLs, then configure the allow through principal based ACL.
