### ISSUE TITLE
NPE during the installation of a config containing a nested loop

### ISSUE THREAD

**Issue by jochenkoschorke** [Netcentric/accesscontroltool#4]
when trying to install the following test config:

- group_config:

   - for mpc IN [ hq, germany, france ]:

       - for lang IN [ de, en ]:

         - fragment-${mpc}-${lang}-section1-edit:

           - name:
             memberOf: 
             path: /dai/groups/f

         - fragment-${mpc}-${lang}-section2-edit:

           - name:
             memberOf: 
             path: /dai/groups/f

         - fragment-${mpc}-${lang}-section3-edit:

           - name:
             memberOf: 
             path: /dai/groups/f

- ace_config:

    - for mpc IN [ hq, germany, france ]:

       - for lang IN [ de, en ]:

         - fragment-${mpc}-${lang}-section1-edit:

           - path: /content/${mpc}/${lang}/passengercars
             permission: allow
             actions: acl_read,acl_edit,delete,modify,read,create,replicate
             privileges: 
             repGlob:

           - path: /content/${mpc}/${lang}/content-pool/marketing-pool/passengercars
             permission: allow
             actions: acl_read,acl_edit,delete,modify,read,create,replicate
             privileges: 
             repGlob:

           - path: /content/dam/hq/passengercars
             permission: allow
             actions: acl_read,acl_edit,delete,modify,read,create,replicate
             privileges: 
             repGlob:

         - fragment-${mpc}-${lang}-section2-edit:

           - path: /content/${mpc}/${lang}/transporters
             permission: allow
             actions: acl_read,acl_edit,delete,modify,read,create,replicate
             privileges: 
             repGlob:

           - path: /content/${mpc}/${lang}/content-pool/marketing-pool/transporters
             permission: allow
             actions: acl_read,acl_edit,delete,modify,read,create,replicate
             privileges: 
             repGlob:

           - path: /content/dam/hq/transporters
             permission: allow
             actions: acl_read,acl_edit,delete,modify,read,create,replicate
             privileges: 
             repGlob:

         - fragment-${mpc}-${lang}-section3-edit:

           - path: /content/${mpc}/${lang}/busses
             permission: allow
             actions: acl_read,acl_edit,delete,modify,read,create,replicate
             privileges: 
             repGlob:

           - path: /content/${mpc}/${lang}/content-pool/marketing-pool/busses
             permission: allow
             actions: acl_read,acl_edit,delete,modify,read,create,replicate
             privileges: 
             repGlob:

           - path: /content/dam/hq/busses
             permission: allow
             actions: acl_read,acl_edit,delete,modify,read,create,replicate
             privileges: 
             repGlob:

I get the following NPE:

13.01.2015 17:42:48.272 *ERROR* [qtp123659800-19062] biz.netcentric.cq.tools.actool.aceservice.impl.AceServiceImpl Exception in AceServiceImpl: {}
java.lang.NullPointerException: null
	at biz.netcentric.cq.tools.actool.helper.AccessControlUtils.getPrivilegeSet(AccessControlUtils.java:407)
	at biz.netcentric.cq.tools.actool.helper.AccessControlUtils.installPermissions(AccessControlUtils.java:495)
	at biz.netcentric.cq.tools.actool.helper.AcHelper.installBean(AcHelper.java:322)
	at biz.netcentric.cq.tools.actool.helper.AcHelper.resetAclInRepository(AcHelper.java:208)
	at biz.netcentric.cq.tools.actool.helper.AcHelper.installPathBasedACEs(AcHelper.java:147)
...

**Comment by ugocei** [comment]
The issue was due to the fact that the actions property of AceBean's was set during validation, but validation is not always called when beans are generated by a loop.

In general, it is a bad idea to have validations perform side effects.
