### ISSUE TITLE
Upgrade to Java 8 (drop support of AEM 6.1)

### ISSUE THREAD

**Issue by kwin** [Netcentric/accesscontroltool#400]
To leverage classes like [java.util.Base64](https://docs.oracle.com/javase/8/docs/api/java/util/Base64.html) we should compile for Java 8. Java 8 is the minimum supported Java version since AEM 6.2. Also AEM 6.1 is out of support since quite a while now (https://helpx.adobe.com/support/programs/eol-matrix.html) so at the same time we should increase the minimum supported AEM version to AEM 6.2 (or newer).

**Comment by tomasalmeida** [comment]
Hi, should the develop branch code be jdk 1.7 compliant? I was trying to compile the code locally and it imports some java 8 lib classes (they are not used).

**Comment by kwin** [comment]
It should be according to the prerequisites in the readme. Please create a new issue to restore Java 7 compatibility.
Update: I prepared https://github.com/Netcentric/accesscontroltool/pull/414 to check API compatibility with Java 7.
