### ISSUE TITLE
Create user interface in Touch UI

### ISSUE THREAD

**Issue by ghenzler** [Netcentric/accesscontroltool#402]
The UI available at /system/console/actool (triggering, downloading the dump, listing/showing the dumps) should be made available in Touch UI (to have it for cases where /system/console is not available)

**Comment by kwin** [comment]
For security reasons it is important though that all operations in that UI takes the session/resource resolver of the current user instead of leveraging a service user.

**Comment by ghenzler** [comment]
> For security reasons it is important though that all operations in that UI takes the session/resource resolver of the current user instead of leveraging a service user.

I agree, however I think a regular user session will rarely succeed because the very broad permissions needed to apply the config will rarely be available to a user session. ATM moment we mostly use the install hook (that uses the session of the request, but for that case it's usually either admin or a deployment user configured in CICD) and the web console/JMX (allowed for `admin` by default or additional groups as configured in web console security provider).

I think the best compromise is to 
* Allow read-only operations to all users that have access to the navigation and touch ui interface content node
* Check for write operations (that is only "Apply config" ATM) if the user has access to the web console 

The current implementation in PR #409 follows that approach.

**Comment by kwin** [comment]
> I think a regular user session will rarely succeed because the very broad permissions needed to apply the config will rarely be available to a user session. 

I don't agree here, this should anyhow only be used by admins. Also this would be a nice way of supporting multitenancy so that different users are only able to apply ACLs  belonging to their tenant.

**Comment by ghenzler** [comment]
"Project-admin-multitenancy" is currently supported via install hooks - a project on a platform can contribute yaml files via their package. For manual (=UI) use cases, currently there is only "one platform admin" that can deploy any config set on that platform. Now the new TouchUI interface follows that pattern.  

@kwin Please create a separate issue to support the "Project-admin-multitenancy" use case better.
