### ISSUE TITLE
ACTool fails with IllegalStateException "No new entries have been set for AccessControlList at ..." in case an action was redundant

### ISSUE THREAD

**Issue by kwin** [Netcentric/accesscontroltool#41]
The issue was caused by the fix for #33 because that one does not correctly consider that installing an action does no always lead to new entries.
One example would be:
First the following AceBean would be installed
```
AceBean [jcrPath=/content/nc_test_hq-approved/en
, permission=deny
, repGlob=null
, actionsString=read
, privilegesString=
, principal=fragment-nc_test_hq-approved-en-passengercars-rmc
, actions=[read]]
```

then this AceBean would be installed
```
AceBean [jcrPath=/content/nc_test_hq-approved/en
, permission=allow
, repGlob=
, actionsString=read
, privilegesString=
, principal=fragment-nc_test_hq-approved-en-passengercars-rmc
, actions=[read]]
```

Since the former is redundant, its ACE is removed when installing the latter. Therefore the number of ACEs is the same before and after the second AceBean has been installed.

**Comment by kwin** [comment]
Remark: You only run into this issue, if your YAML files contain redundant entries!

**Comment by seuck** [comment]
Another example configuration that can trigger this error:

       - path: /content/shared-hub
         permission: allow
         actions: create
         privileges:
         repGlob:

       - path: /content/shared-hub
         permission: allow
         actions: read,modify,create,delete
         privileges:
         repGlob: '/hub-*'

**Comment by gruberroland-netcentric** [comment]
One more valid example:

       - path: /etc/tags
         permission: deny
         actions: read,acl_read
         privileges: 
         repGlob: 

       - path: /etc/tags
         permission: allow
         actions: read,acl_read
         privileges: 
         repGlob: ""

       - path: /etc/tags
         permission: allow
         actions: read,acl_read
         privileges: 
         repGlob: /jcr:*
