### ISSUE TITLE
Touch UI sling:orderBefore node causes other "extra" navitems to disappear

### ISSUE THREAD

**Issue by wimsymons** [Netcentric/accesscontroltool#428]
Hi,

We just updated to version 2.5.0 of your fabulous ACTool, but we're experiencing a bug in the AEM navigation overlays.

There is a sling:orderBefore property on the /apps/cq/core/content/nav/tools/security node. This is set to "deployment".

But we also have our custom TouchUI items in there, as well as an entry of ACS AEM Commons (/apps/cq/core/content/nav/tools/acs-commons).

Issue is that both entries defined in /apps/cq/core/content/nav/tools disappear from the menu due to that property.

When I remove the sling:orderBefore property from /apps/cq/core/content/nav/tools/security it all works perfectly well. I can see our own entry plus the one from ACS AEM Commons.

I experimented with some sling:orderBefore values on our own entry, but I can't seem to find a working combination. 

I have seen this before. Likely a bug in the sling resource merger when using sling:orderBefore.

I'll create a before/after CRX package of the specific tree so you can see for yourself.

Can I suggest to remove that property to fix this issue?
And, could you give me a timeline when a new release would be cut?

Kind regards

Wim

**Comment by kwin** [comment]
@wimsymons With which AEM version do you experience the bug? This bug should IMHO be fixed in the Sling Resource Merger....

**Comment by wimsymons** [comment]
AEM 6.4.4

**Comment by wimsymons** [comment]
[actool-bug.zip](https://github.com/Netcentric/accesscontroltool/files/4099935/actool-bug.zip)
The CRX package where the "VRT Config" entry is missing.

**Comment by wimsymons** [comment]
[actool-fixed.zip](https://github.com/Netcentric/accesscontroltool/files/4099939/actool-fixed.zip)
The CRX package where the "VRT Config" entry is visible.

**Comment by wimsymons** [comment]
I know it should be fixed in the Sling Resource Merger, but you know how long it takes until that makes it into AEM ...

**Comment by wimsymons** [comment]
Hi, I created a PR for this.

**Comment by ghenzler** [comment]
When leaving out `sling:orderBefore="deployment"` in the overlay under `/apps`, the problem was, that the “Security” section was shown at the bottom (instead of its correct position after “Deployment”)

**Comment by wimsymons** [comment]
For me a working navigation is more important than a correctly ordered one.

**Comment by ghenzler** [comment]
We should make sure that both the order is kept and additional items can be added. Maybe the reason why the orderBefore is needed is the fact that the nodetype of the `security` node in libs is different from the one in apps (as delivered by ACTool). 

(I‘m currently only have access via phone and couldn’t check the attached zips)

**Comment by kwin** [comment]
I tried to reproduce this with the attached package from https://github.com/Netcentric/accesscontroltool/issues/428#issuecomment-577385626 but for me it is working fine, i.e. ACS AEM Commons, AC Tool and Cloud Services all show up in the navigation . Can you please tell me with a screenshot, where you are expecting actool and acs aem commons and cloud services to show up?
<img width="1722" alt="Screenshot 2020-01-27 at 12 55 30" src="https://user-images.githubusercontent.com/185025/73172975-8e390e80-4104-11ea-8ab3-7aa3ab5af2b3.png">

Also there is a dedicated test at https://github.com/apache/sling-org-apache-sling-resourcemerger/blob/b771318b64d9dc42678126353f627f7f008f3c9f/src/test/java/org/apache/sling/resourcemerger/impl/CommonMergedResourceProviderTest.java#L401 which verifies that multiple nodes can have the same `sling:orderBefore`!

Regarding order: This is clearly defined at https://sling.apache.org/documentation/bundles/resource-merger.html#child-resource-order. If you don't specify anything then it will show up as last entry. So I think specifying the `sling:orderBefore` is actually correct here!

**Comment by wimsymons** [comment]
Hi @kwin and @ghenzler,

Thanks for your updates.

I've been playing around to find a working combination while keeping your sling:orderBefore.

It is indeed related to the wrong nodetype. Whenever an item encountered is not of type nt:unstructured (the correct underlying nodetype), processing just seems to stop there. Nodes after that seem to be skipped completely.

When I place ACS AEM Commons last (which is a sling:OrderedFolder) *and* change your security folder and our vrt-commons folder to an nt:unstructured, it works, and I see all items properly and in the correct order.

The working setup:  [working-navtools-menu.zip](https://github.com/Netcentric/accesscontroltool/files/4117180/working-navtools-menu.zip)

Screenshots:

ACS Commons as first node:
<img width="274" alt="bad-setup-crx" src="https://user-images.githubusercontent.com/1419117/73175971-ad876a00-410b-11ea-9a36-b6947b15d203.png">
Gives this menu:
<img width="289" alt="bad-setup-menu" src="https://user-images.githubusercontent.com/1419117/73175972-ae200080-410b-11ea-8bcd-1ed35c570218.png">

ACS Commons as last node:
<img width="239" alt="working-setup-crx" src="https://user-images.githubusercontent.com/1419117/73175973-ae200080-410b-11ea-952b-8f2566581a57.png">
Gives this menu:
<img width="277" alt="working-setup-menu" src="https://user-images.githubusercontent.com/1419117/73175974-ae200080-410b-11ea-99ef-d23995343660.png">

I guess I have to open a bug + PR for ACS Commons as well.

Kind regards

Wim

**Comment by kwin** [comment]
@wimsymons Sorry I previously did not install your package correctly. Now if I do that I see all items:

<img width="1656" alt="Screenshot 2020-01-27 at 14 03 05" src="https://user-images.githubusercontent.com/185025/73176918-ede7e780-410d-11ea-887d-ddb78764d61a.png">

All relevant node types are actually `sling:OrderedFolder`: 
<img width="935" alt="Screenshot 2020-01-27 at 14 06 03" src="https://user-images.githubusercontent.com/185025/73177146-84b4a400-410e-11ea-9196-dc6492c90483.png">

So I am not sure what issue your are seeing here.

**Comment by kwin** [comment]
I also checked the component rendering the navigation: /libs/granite/ui/components/endor/navcolumns/navcolumns.jsp. This is completely agnostic of node types!

**Comment by wimsymons** [comment]
I configured the exact same setup: 
<img width="353" alt="CapturFiles-20200127_022813" src="https://user-images.githubusercontent.com/1419117/73178404-75832580-4111-11ea-8788-8a36881bc0f2.png">

This results in this menu:
<img width="283" alt="CapturFiles-20200127_022733" src="https://user-images.githubusercontent.com/1419117/73178455-951a4e00-4111-11ea-9b4a-600f41836d58.png">

Just to recap:
- ACS AEM Commons 3.19.0
- AEM 6.4.4.0
- ACTool 2.5.0

Resource resolver search paths: /apps/ and /libs/.
There is no overlay of /libs/granite/ui/components/endor/navcolumns/navcolumns.jsp at our side.

Do you have anything different than I do?
I'm lost here ...

**Comment by wimsymons** [comment]
Sorry, I inverted security and vrt-commons.
When I mimic yours:
<img width="341" alt="CapturFiles-20200127_023547" src="https://user-images.githubusercontent.com/1419117/73178921-8f713800-4112-11ea-89c0-b18c4a614ab2.png">

I lose VRT Config and it gets replaced with ACS AEM Commons:
<img width="1615" alt="CapturFiles-20200127_023608" src="https://user-images.githubusercontent.com/1419117/73178931-95ffaf80-4112-11ea-916f-be101a6fbca9.png">

**Comment by wimsymons** [comment]
Guys, nothing to do with you.

I found the culprit: https://issues.apache.org/jira/browse/SLING-8296

We are on Sling Resource Merger 1.3.7, and this is fixed in 1.3.10 (in AEM 6.4.7.0).

Sorry for all the trouble and thanks for your help.
