### ISSUE TITLE
/ at the end of a path causes recreation of resource

### ISSUE THREAD

**Issue by stefan-rgb** [Netcentric/accesscontroltool#430]
Hey Guys,

I hope this finds you well.

If you put a / to the end of the path for a goup or user

```
- group_config:
    - mygroup:
      - path: /home/groups/my/groups/
```

The group gets recreated every time you run the apply:

```
12:44:44.907:  Found change of intermediate path for mygroup: /home/groups/my/groups -> /home/groups/my/groups/
12:44:44.914:  Recreated authorizable Group 'mygroup' at path /home/groups/my/groups/d6uCKIHSkE6IEIwvYNcF(retained 3 members of group)
```

Maybe this could be avoided programatically.

Thanks & best regards
Stefan

**Comment by kwin** [comment]
@stefan-rgb Thanks for the report. Can you come up with a PR containing a fix?
