### ISSUE TITLE
Skip in for loop

### ISSUE THREAD

**Issue by ivz-abhinav** [Netcentric/accesscontroltool#448]
Hello - we are trying to use the for loops to create groups in line with growing content.

The advanced guide has been helpful but I am stuck trying to skip the group creation for some paths in the content tree.

The content tree is as follows -

```
/content/site/one
/content/site/two
/content/site/three
```

With the loop its simple to create something like - 

```
FOR w WITH CONTENT IN CHILDREN OF /content/site:
        - ${w.name}-editors:
            - path: /content/dam/site/${w.name}
              permission: allow
              actions: read, create, delete, modify, replicate
```

I only want to create the groups for two and three but not one. The IF conditions mentioned in the advanced guide seem to indicate how to create additional groups if the condition matches. I want to totally skip the group creation if the condition matches.

Any ideas?

**Comment by ghenzler** [comment]
What about `- IF ${w.name ne "one"}:`?

**Comment by ivz-abhinav** [comment]
I eventually created a IF condition similar to @ghenzler suggested above (thanks for the nudge!), referring to a tag instead. So don't need to put the name explicitly in yaml. 

```
- IF ${contains(w["jcr:content"]["cq:tags"][0],'acl')}:
```
This tag `acl` is applied to all sites to be managed by the tool. So serves our use-case.
