### ISSUE TITLE
Provide impersonation configuration

### ISSUE THREAD

**Issue by joerghoh** [Netcentric/accesscontroltool#455]
I have a lot of groups, and for testing I need testusers for each group for easier validation.

But on the other hand side I need everyone to login with a personalized account, so I cannot provide these users with the capability to login, but the users should use the impersonalization feature to impersonate into one of these testusers.

(To ease handling, I create these testusers with a secret password providing just the hash value in the yaml files).

I haven't found a way to create these testusers with the ability that all users can impersonate into them.

**Comment by ghenzler** [comment]
Impersonation is not yet implemented (usually we get away with sharing the test users on lower environments) - it would be good to have this though! (PR welcome)

**Comment by kwin** [comment]
Just for the record. On an API level one needs to call http://jackrabbit.apache.org/api/2.18/org/apache/jackrabbit/api/security/user/User.html#getImpersonation() on the newly created user and then http://jackrabbit.apache.org/api/2.18/org/apache/jackrabbit/api/security/user/Impersonation.html#grantImpersonation-java.security.Principal- on the returned `Impersonation` object. Makes sense to enrich the user configuration (https://github.com/Netcentric/accesscontroltool/blob/develop/docs/Configuration.md#configuration-of-users) by a new property `impersonationAllowedFor` referencing other authorizable ids.
