### ISSUE TITLE
can someone please tell me how to use wildcards in path? (using Adobe 6.4.x latest patch)

### ISSUE THREAD

**Issue by ghost** [Netcentric/accesscontroltool#456]
I have the following lines

    - path: '/content/mysite/en/test*'
      permission: deny
      actions: modify,acl_read

I'm getting this error when installing the package: E Could not process yaml files (javax.jcr.query.InvalidQueryException: java.text.ParseException: Query: /jcr:root/content/mysite/en/test(*)*; expected: <end>)

Any ideas what I could be doing wrong? Thanks

**Comment by puradawid** [comment]
I am having the same issue here:

It says:

`E Could not process yaml files (javax.jcr.query.InvalidQueryException: java.text.ParseException: Query: /jcr:root/conf/site-*(*)/settings/wcm/templates; expected: )`

It looks like asterisk is generated twice and it should close off at the end but it doesn't. I gave up at this.

**Comment by ghenzler** [comment]
Wildcards work for simple cases as described in https://github.com/Netcentric/accesscontroltool/blob/develop/docs/Configuration.md#configuration-of-aces

For more complicated cases please use loops and ifs as described in https://github.com/Netcentric/accesscontroltool/blob/develop/docs/AdvancedFeatures.md#loops-derived-from-content-structure and https://github.com/Netcentric/accesscontroltool/blob/develop/docs/AdvancedFeatures.md#conditional-entries
