### ISSUE TITLE
ACL accesscontroltool Documentation and Usage

### ISSUE THREAD

**Issue by anoopkumargarg** [Netcentric/accesscontroltool#458]
Hi All,
I am going through latest version of this tool . There is not documentation available to use this in touch UI . Could you please help me for the same that how can i use it from  touch UI instead of JMX console
![123](https://user-images.githubusercontent.com/18573017/83641958-dd6be000-a5cb-11ea-8a51-59fc4483dba8.JPG)
?

**Comment by kwin** [comment]
There is https://github.com/Netcentric/accesscontroltool/blob/develop/docs/ApplyConfig.md#touch-ui. Feel free to improve it via PRs.

A related issue is raised in #443, but please be more specific in your description in what exactly you don't understand in that UI.

**Comment by ghenzler** [comment]
@anoopkumargarg Documentation is at https://github.com/Netcentric/accesscontroltool/blob/develop/docs/ApplyConfig.md#touch-ui  - if the problem persists please open a more specific request (best with a PR for the fix)
