### ISSUE TITLE
Can we put the .yaml file under /content/project or /content/dam/project node

### ISSUE THREAD

**Issue by SwatiDusane** [Netcentric/accesscontroltool#459]
Hi Team,

I want to check if I can put the .yaml file under the /content/project_name or /content/dam/project_name node, I tried that it executes the yaml file but no changes are reflecting as given in that yaml file.

Can we also give multiple paths in ace_config so we can set same permissions for mulipltle paths for a group liek below :

- groupname:

       - path: /content/dam/proj,/content/proj
         permission: allow
         actions: read,modify,create,delete,replicate
         privileges: 

 Thanks.

**Comment by ghenzler** [comment]
@SwatiDusane You can apply a config from `/content/dam` without problem, however it is best practice to deliver the yaml files together with the software under `/apps` and have them installed automatically via install hook, compare https://github.com/Netcentric/accesscontroltool/blob/develop/docs/ApplyConfig.md

For applying the same permissions to multiple paths use loops: https://github.com/Netcentric/accesscontroltool/blob/develop/docs/AdvancedFeatures.md#loops
