### ISSUE TITLE
Getting authorizable was already defined in another configuration file on the system even after changing run modes.

### ISSUE THREAD

**Issue by Rampai94** [Netcentric/accesscontroltool#464]
Hi All,

This authorizable was already defined in another configuration file on the system!  Error during processing.

Getting this error even after changing the run modes in the AEM instance.

We had this error initially when the instance was running on two different run modes and we had defined an ACL for each runmode. To fix the issue, we removed one of the run modes and restarted the instance. We have verified that the instance is having only one run mode post restart.

But the package installation still fails with the same error.

Is there any history that I need to delete from the ACTool that can be the cause of this issue?

Thanks,
Ram

**Comment by kwin** [comment]
Which run modes have you tried to change? Some run modes (called Installation Run Modes) can only be initially set in AEM (compare with <https://docs.adobe.com/content/help/en/experience-manager-65/deploying/configuring/configure-runmodes.html>)

**Comment by Rampai94** [comment]
Hi @kwin ,

This was a secondary run mode and not installation run mode that was changed.

We deep dived into the code and found that there is an extended run mode configuration where the conflicting run mode was present even though it was removed from the start script. We have removed it now.

This issue can be closed.

Thanks,
Ram
