### ISSUE TITLE
Creating external groups not possible on AEM 6.4.8

### ISSUE THREAD

**Issue by joerghoh** [Netcentric/accesscontroltool#465]
Trying to create this group with AC Tool 2.5.3 on AEM 6.4.8
```
  - aem-administrator-nonprod:
    - isMemberOf: aem-administrator
      path: /home/groups/mapped
      externalId: aem-administrator-nonprod;ims
```

I get this result:
```
16:10:10.089: ERROR: Could not process yaml files / e=biz.netcentric.cq.tools.actool.authorizableinstaller.AuthorizableCreatorException: java.lang.IllegalStateException: External IDs are not available for your AEM version (aem-administrator-nonprod is using 'aem-administrator-nonprod;ims')
```

But the component ```biz/netcentric/cq/tools/actool/authorizableinstaller/impl/AuthorizableInstallerServiceImpl``` looks good and is active:

![image](https://user-images.githubusercontent.com/337870/85429819-92683b80-b57f-11ea-8e34-3359fa8e1efa.png)

Especially the reference to ```ExternalGroupInstallerServiceImpl``` is present. 

After some trial and error and bundle restarts I found in the logs this:
```
23.06.2020 16:22:23.415 *WARN* [qtp1394303488-12812] biz.netcentric.cq.tools.accesscontroltool.bundle bundle biz.netcentric.cq.tools.accesscontroltool.bundle:2.5.3 (549)[biz.netcentric.cq.tools.actool.authorizableinstaller.impl.AuthorizableInstallerServiceImpl(26010)] : Could not get service from ref [biz.netcentric.cq.tools.actool.authorizableinstaller.impl.ExternalGroupInstallerServiceImpl]
23.06.2020 16:22:23.417 *WARN* [qtp1394303488-12812] biz.netcentric.cq.tools.actool.impl.AcInstallationServiceImpl Using legacy property PID 'AceService.configurationPath' is deprecated, use 'configurationRootPaths' instead. 
23.06.2020 16:22:23.424 *ERROR* [FelixDispatchQueue] biz.netcentric.cq.tools.accesscontroltool.bundle FrameworkEvent ERROR (org.osgi.framework.ServiceException: Service factory exception: org/apache/jackrabbit/oak/spi/security/authentication/external/ExternalGroup)
org.osgi.framework.ServiceException: Service factory exception: org/apache/jackrabbit/oak/spi/security/authentication/external/ExternalGroup
	at org.apache.felix.framework.ServiceRegistrationImpl.getFactoryUnchecked(ServiceRegistrationImpl.java:352)
	at org.apache.felix.framework.ServiceRegistrationImpl.getService(ServiceRegistrationImpl.java:247)
	at org.apache.felix.framework.ServiceRegistry.getService(ServiceRegistry.java:350)
	at org.apache.felix.framework.Felix.getService(Felix.java:3737)
	at org.apache.felix.framework.BundleContextImpl.getService(BundleContextImpl.java:470)
```

This package ```org/apache/jackrabbit/oak/spi/security/authentication/external``` is present in the system and exported by the bundle ``` org.apache.jackrabbit.oak-auth-external```(version 1.8.20) in this way:

```
org.apache.jackrabbit.oak.spi.security.authentication.external,version=2.3.1
org.apache.jackrabbit.oak.spi.security.authentication.external.basic,version=1.3.1
```

But the ac-tool package (version 2.5.3) has this import statement:
```
org.apache.jackrabbit.oak.spi.security.authentication.external; resolution:=optional; version="[0, 2)", 
```

I *think* that it might have worked with AEM 6.4.5, but we recently updated to SP8 as well as to this version of the AC tool (coming from 2.3.2). Can you widen the import statement, so this functionality is working again?

Update: In 2.3.2 the import statement of the bundle looked like this:
```
Import-Package: org.apache.jackrabbit.oak.spi.security.authentication.external;resolution:=optional;version="[1.0,3)"
```
Looks like this has been introduced with 1c50f204c23b56705391908ec33f5f6ed3c4d9a5 (#435)

**Comment by kwin** [comment]
This seems to be a regression of https://github.com/Netcentric/accesscontroltool/commit/1c50f204c23b56705391908ec33f5f6ed3c4d9a5 (#436)

**Comment by kwin** [comment]
I will prepare a PR with a target repo index for the minimum supported version (AEM 6.1.1) and the maximum version (AEM 6.5.8 or AEMaaCS) and make sure we automatically run bnd-resolver-maven-plugin against it.

**Comment by joerghoh** [comment]
Would be happy to see a release real soon, as we have to move forward and 2.3.2 contained quite some issues affecting us.

**Comment by kwin** [comment]
I tried to come up with a fix, but ran into https://github.com/bndtools/bnd/issues/4190. Let's wait if that can be fixed soon, then I will push a more sustainable fix.

**Comment by joerghoh** [comment]
Hi @kwin 

is it possible to create a release based on this fix? We are blocked right now by this issue, so a bugfixed release has some importance to us :-)

Jörg

**Comment by kwin** [comment]
It would help if you could cross-check the linked PR @joerghoh

**Comment by joerghoh** [comment]
I just tested the branch against my local AEM 6.4.5 instance and I see that the package is imported correctly:
```
org.apache.jackrabbit.oak.spi.security.authentication.external,version=2.3.1 from org.apache.jackrabbit.oak-auth-external (95)
```
Haven't tested the tool itself yet, but just looked for this dependency.
