### ISSUE TITLE
By default delete old keystore of user and only optionally extend existing one

### ISSUE THREAD

**Issue by kwin** [Netcentric/accesscontroltool#473]
Currently only new keys are added. But sometimes old ones should be deleted as well. A flag should be added on the user level which allows to do that.

Update: Logic inverted and title adjusted accordingly

**Comment by ghenzler** [comment]
For other properties (ACLs, memberships) the default is to replace what it there - the goal is that what you have the AC Tool config, you can rely on. So I'd suggest to use replace semantics by default and introduce the a config property `appendKeys` (or similar) to leave potentially existing keys untouched

**Comment by kwin** [comment]
I inverted the logic in https://github.com/Netcentric/accesscontroltool/pull/474/commits/2668f1d1ef230b8b405c408b71f517628b6439c2.
