### ISSUE TITLE
Install new ACTool Configs (*.yaml) via Authoring UI

### ISSUE THREAD

**Issue by joerghoh** [Netcentric/accesscontroltool#481]
With AEM as a Cloud Service using the AC Tool is limited to deployment times only. That means that any change which needs to be executed is bound to a code deployment. This can be limiting, especially if new business groups need to be rolled or existing groups need to readjusted.

I would suggest to have a dedicated view, where a YAML file can be uploaded and applied. 

* It must be possible to limit the use of this feature to specific users/groups.
* A proper audit log must be kept with both the content of the uploaded file and the resulting report.
* This feature is limited to the authoring system.

**Comment by kwin** [comment]
There is https://github.com/Netcentric/accesscontroltool/blob/develop/docs/ApplyConfig.md#touch-ui. Doesn't this work for you?

**Comment by joerghoh** [comment]
If it's the same as in the webconsole: No. I would like to upload YAML files directly in this page (not deploy it).

**Comment by kwin** [comment]
The problem with that is, that very often YAML files should be aggregated before installation.  Very rarely all rules are in one big file. Do you want to install the new YAML in the context of existing YAML files or is your use case really just installing the given YAML standalone?

**Comment by joerghoh** [comment]
Assume that I just want to create 2 new groups with a certain set of permissions, which I don't want to do manually.

**Comment by ghenzler** [comment]
So in a way this bypasses the good practice to keep everything in source control - but I do understand that for certain use cases (e.g. for Operations), it can be useful to just install a one-off file (I suppose almost always these changes should go back to source control eventually). 

The Touch UI console is only available for admins, also an audit log of actions/applied files is already kept in /var... so it would be really just adding an upload field and a button and hooking it up to existing functionality. PR welcome :)

**Comment by ghenzler** [comment]
@joerghoh An easy way to achieve what you want to do is to just use the groovy console as follows: 

```
import static org.apache.jackrabbit.commons.JcrUtils.*
import static org.apache.commons.io.IOUtils.*
import biz.netcentric.cq.tools.actool.api.AcInstallationService
def runAcTool(adhocFolder, adhocFile, yaml) {
    putFile(getOrCreateByPath(adhocFolder, "nt:folder", session), adhocFile, "text/yaml", toInputStream(yaml)); session.save();
    return getService(AcInstallationService.class).apply(adhocFolder)
}

runAcTool("/tmp/actool-adhoc", "actool.yaml", """
    
- user_config:
    - test-user:
       - name: "My test user"
         path: /home/users/testusers

""")

```
