### ISSUE TITLE
Is this tool compatible/Support with AMS Managed AEM 6.5.6 (Latest Service Pack) ?

### ISSUE THREAD

**Issue by anoopkumargarg** [Netcentric/accesscontroltool#482]
Please help me for below queries ?

- Is this tool compatible/Support with AEM 6.5.6 (Latest Service Pack) ?

- We hav recently installed latest version of service pack on our AEM servers and noticed , some of permissions got overridden . To fix this we need to redeploy our code and reapply the permissions again ? Is this expected behavior when we are installing any service pack over netcentric ACS tool

**Comment by Positronic-Brain** [comment]
> Is this tool compatible/Support with AEM 6.5.6 (Latest Service Pack)

I do think it is supported - we recently migrated our project to 6.5.6 and we haven't run into any ACL issues so far.

Regarding your second question, if the nodes you're deploying overwrite your custom rep nodes, then you do have to reapply the ACTool.

**Comment by kwin** [comment]
Clarified and not an issue. Therefore closing.
