### ISSUE TITLE
Require AEM 6.4

### ISSUE THREAD

**Issue by kwin** [Netcentric/accesscontroltool#487]
Only AEM 6.4 and above is not yet EOL. We should drop support of older versions to be able to clean up the dependencies.

**Comment by ghenzler** [comment]
this is similar to #400 and should be done together

**Comment by kwin** [comment]
AEM 6.4 does not yet allow usage of principal based service authentication (#563) so probably we should drop AEM 6.4 as well and only support AEM 6.5 and AEMaaCS with the next major version.
