### ISSUE TITLE
Add functions 'containsAnyItem' and 'containsAllItems'

### ISSUE THREAD

**Issue by kwin** [Netcentric/accesscontroltool#507]
The two functions `containsAnyItem` and `containsAllItems` should be added taking two arrays as arguments. They should return `true`  iff any/all of the array items of the 2nd argument is/are contained in array given by the 1st argument.

This is especially helpful for run mode specific conditions where also target run modes are contained in a variable.

**Comment by ghenzler** [comment]
`containsItem(arr, val)` was introduced with #311 (v2.2.0) and is similar, but `containsAnyItem` and `containsAllItems` that allow to pass in two arrays would be a useful addition
