### ISSUE TITLE
System user gets removed from administrators group

### ISSUE THREAD

**Issue by joestieg** [Netcentric/accesscontroltool#511]
Whenever we apply a new AC tool configuration, one of our system users is removed from the administrators group on the author. In our config file, we only define group_config and ace_config. Do we also need to define system users? Thanks.

**Comment by joestieg** [comment]
I've added system user to user_config and this has fixed the problem. Someone might want to update the documentation that warns that system users need to be defined in user_config or they could lose memberships to AEM groups.

**Comment by kwin** [comment]
I think this should be covered already by https://github.com/Netcentric/accesscontroltool/blob/develop/docs/AdvancedFeatures.md#configure-unmanaged-aspects. Feel free to improve the docs though via a PR.

**Comment by ghenzler** [comment]
@joestieg Please reopen if you like to improve the documentation
