### ISSUE TITLE
Allow "user-administrators" group to view the AC tool

### ISSUE THREAD

**Issue by joestieg** [Netcentric/accesscontroltool#514]
How do we give permission to the "user-administrators" group to view the AC tool under "Tools" --> "Security"?  We tried the following but it didn't work: 
 
- path: /apps/netcentric/actool/content
         permission: allow
         privileges: jcr:versionManagement,rep:write,jcr:lockManagement

**Comment by kwin** [comment]
Only read access should be necessary on that path.

**Comment by ghenzler** [comment]
The AC Tool navigation lives at path `/apps/cq/core/content/nav/tools/security/actool`, compare https://github.com/Netcentric/accesscontroltool/blob/develop/accesscontroltool-apps-package/src/main/jcr_root/apps/cq/core/content/nav/tools/security/actool/.content.xml#L6
