### ISSUE TITLE
Installation Hook not picking yaml files

### ISSUE THREAD

**Issue by viveksachdeva** [Netcentric/accesscontroltool#526]
Hey guys,

I recently started using Maven archetype 24 for a project and used embedded and subpacakge to install ACL package with the build. This works alright and I can see package installed.

When I create a yaml file and execute from Touch UI console, it picks up the file and executes it but when I use it via install hook, the hook runs without executing any config file.

In logs I see that there is no config file when it is trying to execute:

```11.12.2020 17:03:52.518 *INFO* [qtp2142917761-16348] org.apache.jackrabbit.vault.packaging.impl.InstallHookProcessorImpl Loading Hook actool: Main-Class = biz.netcentric.cq.tools.actool.installhook.AcToolInstallHook
11.12.2020 17:03:52.519 *INFO* [qtp2142917761-16348] biz.netcentric.cq.tools.actool.impl.AcConfigChangeTracker Execution key hash(,ALL_PATHS,stdRepo) with hash d41d8cd98f00b204e9800998ecf8427e is equal
11.12.2020 17:03:52.519 *INFO* [qtp2142917761-16348-ACTool-Config-Worker] biz.netcentric.cq.tools.actool.impl.AcInstallationServiceImpl *** Applying AC Tool Configuration...
11.12.2020 17:03:52.519 *INFO* [qtp2142917761-16348-ACTool-Config-Worker] biz.netcentric.cq.tools.actool.impl.AcInstallationServiceImpl Running with v2.5.3 on instance id acc428e4-d56b-4ecd-b6b6-7eb5dca1e89b
```

When I open touch UI from Tools > Security. I can see the config path populated with what I configured in XML config file. And when I run it manually, it picks up file under the folder and applies it.

Anyone else faced this issue before? How can I make install hook pick this yaml file during installation?

**Comment by ghenzler** [comment]
@viveksachdeva if you have `*** Applying AC Tool Configuration...` in the log, then it should really run it. Please provide a full log of the server during package installation (you problem should be independent of Maven archetype 24). If you use embedded packages ensure the AC tool package is available before installing the yaml files (e.g. by setting the package dependencies correctly)

**Comment by apelluru** [comment]
@viveksachdeva I am assuming it's already solved. 

- please check your AEM run modes and ac-tool project folders (e.g. config.author / config.author.local)
- biz.netcentric.cq.tools.actool.impl.AcInstallationServiceImpl.cfg.json should contain path
      {
        "configurationRootPaths": [
          "/apps/abc/ac-tool-configs"
        ]
      }
