### ISSUE TITLE
skipForRunmodes

### ISSUE THREAD

**Issue by joestieg** [Netcentric/accesscontroltool#546]
Is it possible to use "skipForRunmodes" configuration in the group definitions so we only need to use one runmode config file?

i.e.
`- AEM-TEST-ADMIN-APP:
       - name: 
         isMemberOf: 
           - campaign-content-authors
           - dam-user
           - workflow-administrators
         skipForRunmodes: prod, preprod

**Comment by ghenzler** [comment]
@joestieg you can use 
```
- DEF prodRunmodes=[prod,preprod]
- IF ${not containsAnyItem(RUNMODES, prodRunmodes)}:
  .... 
```
See also 

https://github.com/Netcentric/accesscontroltool/blob/d33951da91a39a1478d00008c7a6cf77b7135bcd/docs/AdvancedFeatures.md#predefined-variables

and 

https://github.com/Netcentric/accesscontroltool/blob/d33951da91a39a1478d00008c7a6cf77b7135bcd/accesscontroltool-bundle/src/test/resources/test-array-containsAnyItem-function.yaml#L32

**Comment by joestieg** [comment]
Thank you.

**Comment by joestieg** [comment]
I tried applying the following but still unable to get the code to work:

`- group_config:
   
    - DEF environRunmodes=[stage]
    - AEM-MFSCOM-AUTH-ADMIN-APP:

       - name: 
         isMemberOf: 
           - mfs-com-tags-editor    
           - IF ${containsAnyItem(RUNMODES, environRunmodes)}:  
           - FOR items IN ${environRunmodes}:        
           - mfs-com-content-authors
           - workflow-administrators
         path: /home/groups/mfs
`
