### ISSUE TITLE
Create dedicated oakindex package for AEMaaCS

### ISSUE THREAD

**Issue by kwin** [Netcentric/accesscontroltool#549]
The oak index definition package in https://github.com/Netcentric/accesscontroltool/blob/46d64574a0cc952765057433d7dbd80f3652c74e/accesscontroltool-oakindex-package/pom.xml#L67 uses an install hook which cannot be used on AEMaaCS. There should be a simple oak index definition package without the hook for usage for AEMaaCS (in addition to the old one, which is supposed to be used in AEM Classic).

The index definition needs to be converted into a "lucene" index definition as "property" is not supported in AEMaaCS (https://experienceleague.adobe.com/docs/experience-manager-cloud-service/operations/indexing.html?lang=en#changes-in-aem-as-a-cloud-service). An according index definition can be generated with https://oakutils.appspot.com/generate/index.

**Comment by Ganeshbyale** [comment]
Should we manually delete the old /oak:index/repACL as new package is creating /oak:index/repACL-custom-1

**Comment by kwin** [comment]
@Ganeshbyale Yes, you should manually remove the old one if it is still there. Can you please create an issue for that, so that the filter rule in the oakindex-package can be extended to potentially remove the old index if still there?

**Comment by Ganeshbyale** [comment]
sure @kwin I will create an issue.
