### ISSUE TITLE
Bundles are not installed before the AcToolInstallHook is executed when the package is embedded

### ISSUE THREAD

**Issue by alejokf** [Netcentric/accesscontroltool#561]
### Description

When the `accesscontroltool-package` is installed as `embedded` on another project, the bundles are not installed successfully before the `AcToolInstallHook` is executed.

This causes the first deployment on a fresh instance to fail.  A subsequent deployment will work correctly because the bundles are already installed from the first try. However, this represents an issue for AEMaaCS, because we should suppose we can have a fresh instance at any time.

The error we see in the log (an extract) is:
```
18.02.2021 16:59:30.013 *INFO* [JcrInstaller.1] org.apache.sling.installer.provider.jcr.impl.JcrInstaller Registering resource with OSGi installer: [InstallableResource, priority=200, id=/apps/heliux/config/io.wcm.caconfig.extensions.contextpath.impl.AbsoluteParentContextPathStrategy-global.cfg.json, InstallableResource, priority=200, id=/apps/heliux/config/biz.netcentric.sling.caconfig.extensions.v1.persistence.PagePersistenceStrategy.cfg.json, InstallableResource, priority=200, id=/apps/heliux/config/org.apache.sling.installer.provider.jcr.impl.JcrInstaller.cfg.json, InstallableResource, priority=200, id=/apps/heliux/config/io.wcm.caconfig.extensions.persistence.impl.PagePersistenceStrategy.cfg.json, InstallableResource, priority=200, id=/apps/heliux/config/org.apache.sling.commons.log.LogManager.factory.config-groovy.cfg.json, InstallableResource, priority=200, id=/apps/heliux/config/org.apache.sling.caconfig.management.impl.ConfigurationManagementSettingsImpl.cfg.json, InstallableResource, priority=200, id=/apps/heliux/config/com.henkel.wcms.heliux.components.image.v1.services.ImageRenditionService.cfg.json, InstallableResource, priority=200, id=/apps/heliux/config/biz.netcentric.cq.tools.actool.impl.AcInstallationServiceImpl.cfg.json]
18.02.2021 16:59:30.767 *INFO* [OsgiInstallerImpl] org.apache.sling.installer.provider.installhook.OsgiInstallerHook Waiting for 2 bundles / 0 configs to be installed
...
18.02.2021 17:00:28.059 *INFO* [OsgiInstallerImpl] org.apache.sling.installer.provider.installhook.OsgiInstallerHook Waiting for 2 bundles / 0 configs to be installed
18.02.2021 17:00:28.639 *INFO* [FelixLogListener] com.adobe.granite.repository Service [5098, [org.apache.jackrabbit.oak.api.jmx.SessionMBean]] ServiceEvent REGISTERED
18.02.2021 17:00:29.061 *INFO* [OsgiInstallerImpl] org.apache.sling.installer.provider.installhook.OsgiInstallerHook Installable resources [InstallableResource, priority=2000, id=/apps/netcentric/actool/install/27/accesscontroltool-startuphook-bundle-2.7.2.jar, InstallableResource, priority=2000, id=/apps/netcentric/actool/install/accesscontroltool-bundle-2.7.2.jar, InstallableResource, priority=2000, id=/apps/netcentric/actool/config/org.apache.sling.serviceusermapping.impl.ServiceUserMapperImpl.amended-ncActoolSystemUser.config] could not be installed even after waiting 60sec
```

Then:
```
18.02.2021 17:00:37.925 *INFO* [OsgiInstallerImpl] org.apache.sling.audit.osgi.installer TaskResource(url=jcrinstall:/apps/heliux/3rdparty/install/accesscontroltool-package-2.7.2.zip, entity=content-package:Netcentric:accesscontroltool-content-package, state=INSTALL, attributes=[org.apache.sling.installer.api.tasks.ResourceTransformer=:43:71:73:23:824:, package-id=Netcentric:accesscontroltool-content-package:2.7.2, sph-option=INSTALL, Bundle-Version=2.7.2], digest=1613663966776): content package installed
18.02.2021 17:00:37.927 *INFO* [OsgiInstallerImpl] org.apache.jackrabbit.vault.packaging.impl.InstallHookProcessorImpl Loading Hook actool: Main-Class = biz.netcentric.cq.tools.actool.installhook.AcToolInstallHook
18.02.2021 17:00:38.007 *ERROR* [OsgiInstallerImpl] org.apache.jackrabbit.vault.packaging.impl.InstallHookProcessorImpl Error while initializing hook: org.apache.jackrabbit.vault.packaging.PackageException: hook's main class biz.netcentric.cq.tools.actool.installhook.AcToolInstallHook not found: actool
18.02.2021 17:00:38.009 *ERROR* [OsgiInstallerImpl] com.adobe.granite.installer.factory.packages.impl.PackageTransformer Error while processing install task of henkel:heliux-acl-package:2.0.0-SNAPSHOT.
org.apache.jackrabbit.vault.packaging.PackageException: hook's main class biz.netcentric.cq.tools.actool.installhook.AcToolInstallHook not found: actool
	at org.apache.jackrabbit.vault.packaging.impl.InstallHookProcessorImpl$Hook.init(InstallHookProcessorImpl.java:242) [org.apache.jackrabbit.vault:3.4.0]
	at org.apache.jackrabbit.vault.packaging.impl.InstallHookProcessorImpl$Hook.access$300(InstallHookProcessorImpl.java:162) [org.apache.jackrabbit.vault:3.4.0]
	at org.apache.jackrabbit.vault.packaging.impl.InstallHookProcessorImpl.initHook(InstallHookProcessorImpl.java:122) [org.apache.jackrabbit.vault:3.4.0]
	at org.apache.jackrabbit.vault.packaging.impl.InstallHookProcessorImpl.registerHooks(InstallHookProcessorImpl.java:96) [org.apache.jackrabbit.vault:3.4.0]
	at org.apache.jackrabbit.vault.packaging.impl.ZipVaultPackage.prepareExtract(ZipVaultPackage.java:181) [org.apache.jackrabbit.vault:3.4.0]
	at org.apache.jackrabbit.vault.packaging.impl.JcrPackageImpl.extract(JcrPackageImpl.java:393) [org.apache.jackrabbit.vault:3.4.0]
	at org.apache.jackrabbit.vault.packaging.impl.JcrPackageImpl.extract(JcrPackageImpl.java:360) [org.apache.jackrabbit.vault:3.4.0]
	at org.apache.jackrabbit.vault.packaging.impl.JcrPackageImpl.install(JcrPackageImpl.java:354) [org.apache.jackrabbit.vault:3.4.0]
	at com.adobe.granite.installer.factory.packages.impl.PackageTransformer$InstallPackageTask.execute(PackageTransformer.java:350) [com.adobe.granite.installer.factory.packages:1.0.18]
	at org.apache.sling.installer.core.impl.OsgiInstallerImpl.doExecuteTasks(OsgiInstallerImpl.java:918) [org.apache.sling.installer.core:3.11.4]
	at org.apache.sling.installer.core.impl.OsgiInstallerImpl.executeTasks(OsgiInstallerImpl.java:755) [org.apache.sling.installer.core:3.11.4]
	at org.apache.sling.installer.core.impl.OsgiInstallerImpl.run(OsgiInstallerImpl.java:304) [org.apache.sling.installer.core:3.11.4]
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassNotFoundException: Class not found biz.netcentric.cq.tools.actool.installhook.AcToolInstallHook
	at com.adobe.granite.installer.factory.packages.impl.PackageAdminClassLoader.loadClass(PackageAdminClassLoader.java:140) [com.adobe.granite.installer.factory.packages:1.0.18]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at org.apache.jackrabbit.vault.packaging.impl.InstallHookProcessorImpl$Hook.loadMainClass(InstallHookProcessorImpl.java:250) [org.apache.jackrabbit.vault:3.4.0]
	at org.apache.jackrabbit.vault.packaging.impl.InstallHookProcessorImpl$Hook.init(InstallHookProcessorImpl.java:238) [org.apache.jackrabbit.vault:3.4.0]
	... 12 common frames omitted
```

### Workaround
One workaround is to preinstall the `accesscontroltool-package` with the server. However, when working with AEMaaCS this is not an option.

Another workaround that currently works, is to install the package as `subPackage` instead as `embedded`.  This only works if the inclusion of the package as `subPackage` is done in the main container (`alll`) package. If it is added inside another contained package (e.g. `3rd-party-package`), which is included in the main container package as `embedded`, this will not work.

The Cloud Manager build will consider this as a minor code smell ([ImmutableMutableMixedPackage](https://experienceleague.adobe.com/docs/experience-manager-cloud-manager/using/how-to-use/custom-code-quality-rules.html?lang=en#oakpal-packages-immutable)) and the build and deployment will succeed.

However, this could fail in the future since when working with _AEMaaCS_, the packages should be installed as `embedded`, instead of as `subPackage` as pointed out in the official [documentation](https://experienceleague.adobe.com/docs/experience-manager-cloud-service/implementing/developing/aem-project-content-package-structure.html?lang=en#embeddeds). This restrictions seems not to be enforced.

### Root Cause

The difference between using `embedded` and `subPackage` is that the former will add the package under `/apps/my-app/install`, while the latter will add the package under `/etc/packages`.

Also, and most importantly, is that packages included as `embedded` are installed by the [OSGi Installer](https://sling.apache.org/documentation/bundles/osgi-installer.html), but the AC Tool hook relies on the [Installer Vault Package Install Hook](https://sling.apache.org/documentation/bundles/installer-provider-installhook.html), which can't force installation of contained bundles when they are installed by the OSGi Installer.

**Comment by ghenzler** [comment]
Created #606 to improve the documentation

**Comment by kwin** [comment]
With the AC Tool with classifier `cloud` the installer provider install hook is no longer used for this reason (https://github.com/Netcentric/accesscontroltool/blob/c35506099f10851a71a6ddbc838526747004d2bc/accesscontroltool-package/pom.xml#L145). Still this requires you to manually make sure that the bundle is started before the package leveraging the ACTool install hook is installed.

**Comment by ghenzler** [comment]
See https://github.com/Netcentric/accesscontroltool/blob/develop/docs/Installation.md for improved documentation.

**Comment by royteeuwen** [comment]
@ghenzler  I don't see how the documentation that you provide actually fixes the issue locally? Locally we still have the same problem that on a fresh install, the install hook is not available yet because the bundle might not be active yet.

Any workaround / fix available so far yet?

**Comment by gauravs23** [comment]
@royteeuwen Were you able to find any resolution for the issue of first build not installing the packages correctly on local on fresh instance? We are still facing that same issue where on the first install on local instance the packages are NOT installed and a rebuild needs to be done.

@ghenzler / @kwin / @alejokf - Any comments from your end on this issue would be very helpful as well.

**Comment by royteeuwen** [comment]
Hey @gauravs23 ,

we have solved this with a workaround, namely adding an extra content package, containing only the frameworks

when executing the following command in the root, it will first install the frameworks and then the all package:

mvn clean install -PautoInstallSinglePackage

This solves all missing dependency issues.

Another thought around how to solve this is by using an Osgi Condition that is only activated after all bundles / packages are installed, and use this to activate the StartupHook for executing the rules, but this is a bigger effort, didn’t get around that yet

**Comment by priyankamalviya** [comment]
Hey @ghenzler / @kwin / @alejokf - I am seeing the same error when tryin to install actool 3.0.10 in aem cloud sdk. --" +- <MAJOR> InstallHook error: java.lang.ClassNotFoundException "hook's main class biz.netcentric.cq.tools.actool.installhook.AcToolInstallHook not found: actool" 
[INFO]   net.adamcin.oakpal.core/basic/filterSets" . I am new to actool and I followed this tutorial to install actool on cloud - https://www.linkedin.com/pulse/aem-how-configure-netcentric-aemcaas-veena-vikraman/. Please provide help. Thank you
