### ISSUE TITLE
Refactor service user mapping to format with principals and define principal-based access control setup

### ISSUE THREAD

**Issue by anchela** [Netcentric/accesscontroltool#563]
@kwin as mentioned with the acs-aem-commons package the service user mappings defined in https://github.com/Netcentric/accesscontroltool/blob/develop/accesscontroltool-package/src/main/jcr_root/apps/netcentric/actool/config/org.apache.sling.serviceusermapping.impl.ServiceUserMapperImpl.amended-ncActoolSystemUser.config
should be adjusted to use the format 'service:subservice=[principalName]':
```
biz.netcentric.cq.tools.accesscontroltool.bundle=[actool-service]
biz.netcentric.cq.tools.accesscontroltool.startuphook.bundle=[actool-service]
```
this results in service resourceresolver/session to only come with the permissions declared (and needed) for the service user(s) to perform the tasks the service is designed for and doesn't include any declared or inherited group membership.

with the new mapping format also principal-based access control setup can be used (either in repo-init or in content packages). in repo init this would look for the actool-service something like follows (i didn't test that for correctness).... but content packages should work as well afaik.

```
create service user actool-service with forced path system/cq:services/netcentric/accesscontroltool
set principal ACL for actool-service
allow jcr:all on /
allow jcr:all on :repository
end
```

see however SLING-10070 for an option in the content-package-feature-model converter that will allow to enforce principal-based ac setup for service users that have ac-setup defined in content packages _and_ defined mapping format with [one,or,multiple,principal,names].
hope it helps

**Comment by kwin** [comment]
This is related to #544 but principal based authorization requires AEM 6.5 or newer.
