### ISSUE TITLE
Deployment fails on AEMaaCS after upgrading to 2.8.0

### ISSUE THREAD

**Issue by alejokf** [Netcentric/accesscontroltool#570]
### Error
When trying to deploy our project to AEMaaCS, after upgrading accesscontroltool to version [2.8.0](https://github.com/Netcentric/accesscontroltool/releases/tag/2.8.0), the **Build Images** step fails with the following error in the logs:
```
[ERROR] repoinit: Parsing error in repoinit from extension : Encountered "" at line 1798, column 36.
Was expecting one of:
    
[ERROR] Analyser detected errors on feature 'com.adobe.granite:aem-ethos-app-image:slingosgifeature:aem-runtime-application-golden-publish-prod:1.0.0-SNAPSHOT'. See log output for error messages.
INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:37 min
[INFO] Finished at: 2021-03-22T14:29:32Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.sling:slingfeature-maven-plugin:1.4.22:analyse-features (analyze-aggregates) on project aem-ethos-app-image: One or more feature analyser(s) detected feature error(s), please read the plugin log for more details -> [Help 1]
```

**Note**
Version **2.8.0** introduces the usage of [Repo Init](https://experienceleague.adobe.com/docs/experience-manager-cloud-service/implementing/developing/aem-project-content-package-structure.html?lang=en#repo-init).

### Cause
This error message is not very useful to understand the issue, so I had to deep dive and do some tests. I found the following:
The issue is caused in the RepoInit Analyzer from [sling-org-apache-sling-feature-analyser](https://github.com/apache/sling-org-apache-sling-feature-analyser). This Analyser project is used by:

1. The [aemanalyser-maven-plugin](https://github.com/adobe/aemanalyser-maven-plugin): for this plugin, the repoinit analyzer has been [temporarily disabled](https://github.com/adobe/aemanalyser-maven-plugin/commit/9f6e2d20b6b936311e702e7d9f05173cb3adaa57#diff-25a6e2d335a3b31bb9785a2bd931dd1329a57f6dda4a35b4e0989dcd7e2aff17) in version 0.9.2.
2. The [sling-slingfeature-maven-plugin](https://github.com/apache/sling-slingfeature-maven-plugin): this plugin still uses the repoinit analyzer and it is actually the plugin being executed by Adobe Cloud Manager when the Build Image step fails.

One workaround would be to also disable the RepoInit analyser when running the **sling-slingfeature-maven-plugin**, which is possible trough the **excludeTask** property in the plugin configuration, but this plugin is set and run by the Adobe Cloud Manager and we don't have control over it.

Packages are transformed in Cloud Manager and it is not possible to obtain them to inspect them. But since we were able to isolate the single change that made our build fail (upgrading accesscontrol tool to 2.8.0) we are sure the problem must be coming from the repoinit script added in this version.

The error log says the problem is "...at line 1798, column 36". The line is 1798 because probably the repoinit scripts are joined together in a single one when the package transformations are done. Column 36 corresponds precisely to the start of `with forced path` in the first line of the accesscontroltool [repoinint script](https://github.com/Netcentric/accesscontroltool/blob/develop/accesscontroltool-package/src/main/jcr_root-cloud/apps/netcentric/actool/config/org.apache.sling.jcr.repoinit.RepositoryInitializer%7Eactool.config#L1).

The `with forced path` syntax works correctly on a local environment (tested with AEM version `2021.3.4997.20210303T022849Z-210225`), however it is not in the [Apache Sling Repo Init documentation](https://sling.apache.org/documentation/bundles/repository-initialization.html). My guess is that this is a new syntax that is not part of the `RepoInitParser` version (used by the `CheckRepoinit` analyzer) that is used by Cloud Manager.

**Note**
This error is related to [SLING-10215](https://issues.apache.org/jira/browse/SLING-10215).

### Proposed Solution
To confirm that the problem comes from this syntax, I removed it and then created and uploaded temporal accesscontrol tool artefacts (on a private azure repo) with this change. The build in Cloud Manager worked correctly after that.

If the `actool-service` user does not need to be located in `system/cq:services/actool`, I think this can be removed from the repoinit script.

**Comment by kwin** [comment]
This is an issue, which is fixed in newer AEM versions. It is not(!) related to the repoinit scripts of ACTool. Just upgrade to a newer version, i.e. 2021.3.5087.20210322T071003Z-210225 works fine for other Cloud Manager AEMaaCS builds.

**Comment by kwin** [comment]
The system user`actool-service` needs to be located below `system/cq:services` because only there principal-based authorization works (https://github.com/Netcentric/accesscontroltool/issues/563).

**Comment by alejokf** [comment]
Right, I updated the AEM version in Cloud Manager and this solved the issue.
