### ISSUE TITLE
Cloud Manager sonar analysis is failing due to critical issues related with CQRules:CQBP-84

### ISSUE THREAD

**Issue by OleksandrBarybin** [Netcentric/accesscontroltool#584]
Required information:
AEMaaCS version: 2021.3.5087.20210322T071003Z
ACTool version: 2.8.0
Reproducible on Latest? yes

Expected Behavior
Cloud Manager code analysis is ok

Actual Behavior
Cloud Manager code analysis is failing and breaking the build as a result due to Sonar critical issue [CQRules:CQBP-84](https://www.adobe.com/go/aem_cmcq_cqbp-84_en)

Steps to Reproduce

- Deploy project that has accesscontroltool-package dependency 
- Wait until **Code Scanning** step will be reached and will fail
- Click on "Download Details" button
- Observe next critical error

`The product interface org.apache.jackrabbit.api.security.JackrabbitAccessControlEntry annotated with @ProviderType should not be implemented by custom code. Detected in biz.netcentric.cq.tools.actool.helper.AceWrapper contained in /apps/netcentric/actool/install/accesscontroltool-bundle-2.8.0.jar.
`

Links
Related CQ rule documentation: https://experienceleague.adobe.com/docs/experience-manager-cloud-manager/using/how-to-use/custom-code-quality-rules.html?lang=en#product-apis-annotated-with-providertype-should-not-be-implemented-or-extended-by-customers

**Comment by kwin** [comment]
I think this should be quite easy to fix by letting the `AceWrapper` just use the composite pattern (i.e. expose the underlying ACE in a getter method) instead of implementing the interface itself. @OleksandrBarybin Can you come up with a PR?

**Comment by OleksandrBarybin** [comment]
@kwin PR is opened, hope everything is correct  https://github.com/Netcentric/accesscontroltool/pull/585

**Comment by kwin** [comment]
Merged in https://github.com/Netcentric/accesscontroltool/commit/eacf7f450916ffbbe4adb04b351241e0fb3d9bce
