### ISSUE TITLE
Make user password encryption compatible with AEM CloudService

### ISSUE THREAD

**Issue by elagun** [Netcentric/accesscontroltool#587]
When creating users in the YAML configuration their password needs to be encrypted. Using Crypto Support for this is not feasible in AEM CS, so there's currently no way to create users with passwords on AEM CS (unless you check-in the password in clear text, which you shouldn't). 

The way to store environment specific encrypted values/secrets in AEM CS is through CloudManager secrets [0].
However, CloudManager secrets work within OSGI configs only and not in the custom AC Tool YAML config files. Hence the AC Tool ideally would support the use of CM secrets.

[0] https://experienceleague.adobe.com/docs/experience-manager-cloud-service/implementing/deploying/configuring-osgi.html?lang=en#how-to-choose-the-appropriate-osgi-configuration-value-type

**Comment by kwin** [comment]
ACTool already supports secrets: https://github.com/Netcentric/accesscontroltool/blob/develop/docs/AdvancedFeatures.md#interpolate-values

**Comment by elagun** [comment]
@kwin Thanks for the info. Than it would be nice if you could update the documentation about user configuration in https://github.com/Netcentric/accesscontroltool/blob/develop/docs/Configuration.md. It's not mentioned there that CM secrets can be used on AEM CS, but only Crypto Support encrypted values. Thanks.

**Comment by kwin** [comment]
@elagun Please come up with a proposal via a PR for enhancing the documentation.
