### ISSUE TITLE
Critical Bug flagged by Cloud Manager

### ISSUE THREAD

**Issue by ho-gabriel** [Netcentric/accesscontroltool#588]
AEM Version 6.5.9
Netcentric Access Control Tool Package: 3.0.0
Reproducible on latest? Yes

Issue:
The product interface org.apache.jackrabbit.api.security.JackrabbitAccessControlEntry annotated with @ProviderType should not be implemented by custom code. Detected in biz.netcentric.cq.tools.actool.helper.AceWrapper contained in /apps/netcentric/actool/install/accesscontroltool-bundle-3.0.0.jar.

Rule: CQRules:CQBP-84

Documentation: https://www.adobe.com/go/aem_cmcq_cqbp-84_en

**Comment by kwin** [comment]
This is a duplicate of #584 and already fixed in the last release.
