### ISSUE TITLE
AaaCS: Reprocess dependent YAML files

### ISSUE THREAD

**Issue by aanchalsikka** [Netcentric/accesscontroltool#593]
Hello

We are using the tool to set up permissions on AaaCS.

We have permissions under:

- global.author
- group.author.dev
- group.author.prod
- group.author.stage

**Issue**: If there is a change in global.author, file is reprocessed. This means the groups are recreated.

Consider when files in runmode specific folders are not changed, thus not reprocessed.
Thus, if Group A in global.author is a member of group in group.author.dev the association is broken, since group is created again.

**Query**: How could we trigger processing of dependent YAML files present in a different folder.

**Comment by ghenzler** [comment]
Changes to all mentioned folders above should be correctly applied. For AEMaaCS this means

* /apps and /libs during image build
* other root folders during image start

you can also manually trigger installation for the the mutable folders (not /apps and /libs )  via https://github.com/Netcentric/accesscontroltool#user-interface

**Comment by ghenzler** [comment]
Please reopen with a more detailed description if the issue persists
