### ISSUE TITLE
System user creation no longer works

### ISSUE THREAD

**Issue by gruberroland-netcentric** [Netcentric/accesscontroltool#62]
Since 1.8.0 the creation of system users no longer works. 
I get an IllegalStateException that Boolean is an unexpected class when parsing the "true".

Example:

- user_config:

    - example-tags:

       - name: 
         isMemberOf: example-system-tags
         path: m
         isSystemUser: true

**Comment by gruberroland-netcentric** [comment]
Looks like YamlMacroProcessorImpl needs to handle Booleans, too.

**Comment by ghenzler** [comment]
@gruberroland-netcentric there is probably a workaround possible by using quotes  isSystemUser: "true" or even  isSystemUser: ${'true '} - but obviously this needs to be fixed, I will take care of it ASAP.

**Comment by sbrinkmann** [comment]
The work around works

**Comment by ghenzler** [comment]
Merged pull request and assigned milestone 1.8.3 (as 1.8.2 is already released)
