### ISSUE TITLE
Use ResourceChangeListeners

### ISSUE THREAD

**Issue by joerghoh** [Netcentric/accesscontroltool#621]
I found that  [biz.netcentric.cq.tools.actool.configuploadlistener.impl.UploadListenerServiceImpl$AcToolConfigUpdateListener](https://github.com/Netcentric/accesscontroltool/blob/cec8d5244bf3b1c0278ec71b2eaefa4b32f71f6e/accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/configuploadlistener/impl/UploadListenerServiceImpl.java#L114) is registered to listen for OSGI Resource Events.

This approach is deprecated by now, instead you should use the ResourceChangeListener approach, as indicated in the [Sling documentation](https://sling.apache.org/documentation/the-sling-engine/resources.html#osgi-event-based-resource-changes-deprecated-1)

**Comment by ghenzler** [comment]
@joerghoh we don't really recommend to use it (see https://github.com/Netcentric/accesscontroltool/blob/develop/docs/ApplyConfig.md#upload-listener-service, it's more there for historical reasons), but yes, it should be upgraded to use the ResourceChangeListener approach

**Comment by royteeuwen** [comment]
@ghenzler It would be nice because the install hook way for local development polutes the configuration for the cloud deployment, forcing it to be put on mixed instead of container

**Comment by ghenzler** [comment]
@royteeuwen The upload listener would not allow to restrict/allow access to product functionality in /libs and /apps, using a separate package for all yaml files with type mixed ala https://github.com/Netcentric/accesscontroltool/blob/develop/docs/Installation.md#declaring-the-dependency is a good compromise from our experience.
