### ISSUE TITLE
Make changes to remove the old repACL node 

### ISSUE THREAD

**Issue by Ganeshbyale** [Netcentric/accesscontroltool#629]
As there is a new node /oak:index/repACL-custom-1 created to comply with AEMaaCS.
Please make necessary changes to delete the old node /oak:index/repACL.

**Comment by kwin** [comment]
The node has been renamed in https://github.com/Netcentric/accesscontroltool/commit/dd7e51e09466fc999fdeffa25156ac913f462e9a, but the filter rule for the old node name has been completely removed. Instead a filter rule containing the old node name with type="cleanup" should still be contained in the package.
This originally came up at https://github.com/Netcentric/accesscontroltool/issues/549#issuecomment-1089109198.
