### ISSUE TITLE
Allow AC Tools to use "user-administrators" or "Others" group execution.

### ISSUE THREAD

**Issue by Hiro0208** [Netcentric/accesscontroltool#639]
[question]

*For system security reasons, a user who is not allowed to access /system/console intentionally wants to run an actool in Touch UI

Using Touch UI: http://<host>:<port>/mnt/overlay/netcentric/actool/content/overview.html/actool

Refer to #514.

How do I give the "user-administrators" group permission to run the AC tool under "Tools" -> "Security"?

I have granted all permissions to the following, but it did not work

Path: /apps/netcentric/actool/content
Path :/apps/cq/core/content/nav/tools/security/actool,

**Comment by kwin** [comment]
Please raise questions in https://github.com/Netcentric/accesscontroltool/discussions. This is only for tracking issues.
