### ISSUE TITLE
getRepPolicyNodes is not backed by an index

### ISSUE THREAD

**Issue by thomashartm** [Netcentric/accesscontroltool#64]
When installing ACLs a large number of the following warning messages appear in the log file, while the whole process takes almost half an hour on a repo of approx 4 million nodes.
It seems to me that the query in QueryHelper.getRepPolicyNodes line 89 is not backed by any index?

10.03.2016 08:16:10.351 *WARN* [qtp123593292-1375] org.apache.jackrabbit.oak.spi.query.Cursors$TraversingCursor Traversed 4000 nodes with filter Filter(query=SELECT * FROM [rep:ACL] WHERE ISDESCENDANTNODE([/apps]), path=/apps//*); consider creating an index or changing the query
10.03.2016 08:16:10.668 *WARN* [qtp123593292-1375] org.apache.jackrabbit.oak.spi.query.Cursors$TraversingCursor Traversed 5000 nodes with filter Filter(query=SELECT * FROM [rep:ACL] WHERE ISDESCENDANTNODE([/apps]), path=/apps//*); consider creating an index or changing the query
10.03.2016 08:16:10.845 *WARN* [qtp123593292-1375] org.apache.jackrabbit.oak.spi.query.Cursors$TraversingCursor Traversed 6000 nodes with filter Filter(query=SELECT * FROM [rep:ACL] WHERE ISDESCENDANTNODE([/apps]), path=/apps//*); consider creating an index or changing the query
10.03.2016 08:16:10.863 *WARN* [qtp123593292-1375] org.apache.jackrabbit.oak.spi.query.Cursors$TraversingCursor Traversed 7000 nodes with filter Filter(query=SELECT * FROM [rep:ACL] WHERE ISDESCENDANTNODE([/apps]), path=/apps//*); consider creating an index or changing the query
10.03.2016 08:16:10.899 *WARN* [qtp123593292-1375] org.apache.jackrabbit.oak.spi.query.Cursors$TraversingCursor Traversed 1000 nodes with filter Filter(query=SELECT * FROM [rep:ACL] WHERE ISDESCENDANTNODE([/content]), path=/content//*); consider creating an index or changing the query
10.03.2016 08:16:10.924 *WARN* [qtp123593292-1375] org.apache.jackrabbit.oak.spi.query.Cursors$TraversingCursor Traversed 2000 nodes with filter Filter(query=SELECT * FROM [rep:ACL] WHERE ISDESCENDANTNODE([/content]), path=/content//*); consider creating an index or changing the query
10.03.2016 08:16:10.952 *WARN* [qtp123593292-1375] org.apache.jackrabbit.oak.spi.query.Cursors$TraversingCursor Traversed 3000 nodes with filter Filter(query=SELECT * FROM [rep:ACL] WHERE ISDESCENDANTNODE([/content]), path=/content//*); consider creating an index or changing the query
10.03.2016 08:16:10.962 *WARN* [qtp123593292-1375] org.apache.jackrabbit.oak.spi.query.Cursors$TraversingCursor Traversed 4000 nodes with filter Filter(query=SELECT * FROM [rep:ACL] WHERE ISDESCENDANTNODE([/content]), path=/content//*); consider creating an index or changing the query
10.03.2016 08:16:10.976 *WARN* [qtp123593292-1375] org.apache.jackrabbit.oak.spi.query.Cursors$TraversingCursor Traversed 5000 nodes with filter Filter(query=SELECT * FROM [rep:ACL] WHERE ISDESCENDANTNODE([/content]), path=/content//*); consider creating an index or changing the query
10.03.2016 08:16:10.985 *WARN* [qtp123593292-1375] org.apache.jackrabbit.oak.spi.query.Cursors$TraversingCursor Traversed 6000 nodes with filter Filter(query=SELECT * FROM [rep:ACL] WHERE ISDESCENDANTNODE([/content]), path=/content//*); consider creating an index or changing the query
10.03.2016 08:16:10.997 *WARN* [qtp123593292-1375] org.apache.jackrabbit.oak.spi.query.Cursors$TraversingCursor Traversed 7000 nodes with filter Filter(query=SELECT * FROM [rep:ACL] WHERE ISDESCENDANTNODE([/content]), path=/content//*); consider creating an index or changing the query
10.03.2016 08:16:11.012 *WARN* [qtp123593292-1375] org.apache.jackrabbit.oak.spi.query.Cursors$TraversingCursor Traversed 8000 nodes with filter Filter(query=SELECT * FROM [rep:ACL] WHERE ISDESCENDANTNODE([/content]), path=/content//*); consider creating an index or changing the query
10.03.2016 08:16:11.022 *WARN* [qtp123593292-1375] org.apache.jackrabbit.oak.spi.query.Cursors$TraversingCursor Traversed 9000 nodes with filter Filter(query=SELECT * FROM [rep:ACL] WHERE ISDESCENDANTNODE([/content]), path=/content//*); consider creating an index or changing the query
10.03.2016 08:16:11.030 *WARN* [qtp123593292-1375] org.apache.jackrabbit.oak.spi.query.Cursors$TraversingCursor Traversed 10000 nodes with filter Filter(query=SELECT * FROM [rep:ACL] WHERE ISDESCENDANTNODE([/content]), path=/content//*); consider creating an index or changing the query
10.03.2016 08:16:11.041 *WARN* [qtp123593292-1375] org.apache.jackrabbit.oak.spi.query.Cursors$TraversingCursor Traversed 11000 nodes with filter Filter(query=SELECT * FROM [rep:ACL] WHERE ISDESCENDANTNODE([/content]), path=/content//*); consider creating an index or changing the query
10.03.2016 08:16:11.055 *WARN* [qtp123593292-1375] org.apache.jackrabbit.oak.spi.query.Cursors$TraversingCursor Traversed 12000 nodes with filter Filter(query=SELECT * FROM [rep:ACL] WHERE ISDESCENDANTNODE([/content]), path=/content//*); consider creating an index or changing the query
10.03.2016 08:16:11.073 *WARN* [qtp123593292-1375] org.apache.jackrabbit.oak.spi.query.Cursors$TraversingCursor Traversed 13000 nodes with filter Filter(query=SELECT * FROM [rep:ACL] WHERE ISDESCENDANTNODE([/content]), path=/content//*); consider creating an index or changing the query
10.03.2016 08:16:11.089 *WARN* [qtp123593292-1375] org.apache.jackrabbit.oak.spi.query.Cursors$TraversingCursor Traversed 14000 nodes with filter Filter(query=SELECT * FROM [rep:ACL] WHERE ISDESCENDANTNODE([/content]), path=/content//*); consider creating an index or changing the query

**Comment by kwin** [comment]
This should be backed by the index definition in https://github.com/Netcentric/accesscontroltool/blob/develop/accesscontroltool-oakindex-package/src/main/jcr_root/_oak_index/repACL.xml. Please check within your server whether that index definition node is there.

**Comment by thomashartm** [comment]
You are right the index definition is missing.
