### ISSUE TITLE
AEMaaCS : Netcentric package failing in AEM analyzer

### ISSUE THREAD

**Issue by varsha-deora** [Netcentric/accesscontroltool#646]
Failed to execute goal on project aem-smart-project.analyse: Could not resolve dependencies for project com.smart:aem-smart-project.analyse:aem-analyse:0.0.1-SNAPSHOT: The following artifacts could not be resolved: biz.netcentric.cq.tools.accesscontroltool:accesscontroltool-package:content-package:cloud:3.0.4, biz.netcentric.cq.tools.accesscontroltool:accesscontroltool-apps-package:content-package:3.0.4, biz.netcentric.cq.tools.accesscontroltool:accesscontroltool-content-package:content-package:3.0.4: Failure to find biz.netcentric.cq.tools.accesscontroltool:accesscontroltool-package:content-package:cloud:3.0.4 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -

Getting the following error. Current versions:
Analyzer version - 1.4.8
Netcentric Version - 3.0.4

Tried with latest Analyzer version - 1.4.18
(As per https://mvnrepository.com/artifact/com.adobe.aem/aemanalyser-maven-plugin/1.4.0)
and Also Latest netcentric version - 3.0.5
Same error persists

Detailed reference of what is included in POM:
https://www.linkedin.com/pulse/aem-how-configure-netcentric-aemcaas-veena-vikraman/

**Comment by kwin** [comment]
Try with type "zip". Using type "content-package" requires filevault-package-maven-plugin to be loaded with extensions (https://github.com/apache/jackrabbit-filevault-package-maven-plugin/blob/master/src/site/markdown/index.md#usage)
