### ISSUE TITLE
Failing validation of accesscontroltool-apps-package due to include filters

### ISSUE THREAD

**Issue by royteeuwen** [Netcentric/accesscontroltool#655]
When using the aemanalyser to validate also the sub packages of the 'all' bundle in AEMaaCS, I get the following exception:

[INFO] Start validating sub package '/Users/royteeuwen/Development/MyProject/my-project-aem-cloud/all/target/my-project-aem-cloud.all-1.0.0-SNAPSHOT.zip/jcr_root/apps/my-project-packages/content/install/b2c.all-1.9.0.zip/jcr_root/apps/b2c-vendor-packages/application/install/accesscontroltool-package-3.0.7-cloud.zip/jcr_root/apps/netcentric/actool/install/accesscontroltool-apps-package-3.0.7.zip'...
[INFO] Due to package type 'application' emit error for every undefined filter root ancestor
[INFO] Using 6 validators for package of type APPLICATION: jackrabbit-filter (org.apache.jackrabbit.vault.validation.spi.impl.AdvancedFilterValidator), jackrabbit-properties (org.apache.jackrabbit.vault.validation.spi.impl.AdvancedPropertiesValidator), jackrabbit-docviewparser (org.apache.jackrabbit.vault.validation.spi.impl.DocumentViewParserValidator), jackrabbit-duplicateuuid (org.apache.jackrabbit.vault.validation.spi.impl.DuplicateUuidValidator), jackrabbit-oakindex (org.apache.jackrabbit.vault.validation.spi.impl.OakIndexDefinitionValidator), jackrabbit-packagetype (org.apache.jackrabbit.vault.validation.spi.impl.PackageTypeValidator)
[ERROR] ValidationViolation: Package of type 'APPLICATION' is not supposed to contain includes/excludes below any of its filters! @ META-INF/vault/filter.xml, validator: jackrabbit-packagetype

**Comment by kwin** [comment]
There is no other reasonable option for overlays unfortunately (compare with https://issues.apache.org/jira/browse/JCRVLT-403). Just relax the validation rules in that regard.
