### ISSUE TITLE
Immutable paths like /libs and /apps are being skipped while applying ACLs and repo-init works

### ISSUE THREAD

**Issue by Rampai94** [Netcentric/accesscontroltool#665]
We are using AC Tool release version 3.0.6 with AEM as Cloud release version 2023.2.11289.20230224T170559Z.

We have a use-case to allow read access to /libs/workflow/scripts to one of our system users and unfortunately, this doesn't seem to be working using AC Tool off late. This used to work earlier but something that is breaking only recently so could be due to the Adobe release. 

Please can this be investigated further and feature to include immutable path ACLs be part of AC tool itself so that we do not have to maintain separate repo-init scripts for /apps and /libs for service users.

**Comment by kwin** [comment]
Without any logs it is impossible to investigate. Please share those (Logs are accessible at `/mnt/overlay/netcentric/actool/content/overview.html`, https://github.com/Netcentric/accesscontroltool#user-interface). In general ACLs on immutable content are supported.

**Comment by Rampai94** [comment]
Closing this ticket. Logs indicate that this was due to a code change on our end.
