### ISSUE TITLE
Cloud Manager is reporting 2 Critical issues degrading the code reliability scores

### ISSUE THREAD

**Issue by thcharan** [Netcentric/accesscontroltool#673]
Netcentric:accesscontroltool-package:3.0.6 | 0 | The product interface org.apache.jackrabbit.api.security.user.Query annotated with @ProviderType should not be implemented by custom code. Detected in biz.netcentric.cq.tools.actool.dumpservice.impl.DumpServiceImpl$1 contained in /apps/netcentric/actool/install/accesscontroltool-bundle-3.0.6.jar. | Bug | Critical | 30m | CQRules:CQBP-84 | cqsoftwarequality | https://www.adobe.com/go/aem_cmcq_cqbp-84_en

Netcentric:accesscontroltool-package:3.0.6 | 0 | The product interface org.apache.jackrabbit.api.security.user.Query annotated with @ProviderType should not be implemented by custom code. Detected in biz.netcentric.cq.tools.actool.authorizableinstaller.impl.AuthInstallerUserManagerPrefetchingImpl$1 contained in /apps/netcentric/actool/install/accesscontroltool-bundle-3.0.6.jar. | Bug | Critical | 30m | CQRules:CQBP-84 | cqsoftwarequality | https://www.adobe.com/go/aem_cmcq_cqbp-84_en

**Comment by kwin** [comment]
Another duplicate of #671

**Comment by thcharan** [comment]
@kwin  - thank you.
