### ISSUE TITLE
Unable to update ace_config for existing group

### ISSUE THREAD

**Issue by santhoshs** [Netcentric/accesscontroltool#68]
I've two YAML config files, first file contains the group_config and ace_config of a 'GroupA'.

In second YAML file, I declared only 'ace_config' of 'GroupA', but when it's trying to execute both file, it's setting the permission only from second YAML file, but the first file 'ace_config' is skipped.

This is not the same case for user config, for users the 'ace_config' are working with two separate files.

 Please let me know if you need more details, appreciate your help in looking at this issue. Thanks!

**Comment by gruberroland-netcentric** [comment]
Hi, can you provide a small example that shows the error? This also happens with the latest version?

**Comment by santhoshs** [comment]
Hi, Please check the attached yaml-config.zip, it's having two yaml config files.

I've enabled ACL upload listener to specific folder location in crxde and i'm uploading the configs to apply the groups permission.

First please upload 'file-b.yaml' and then 'file-a.yaml', after uploading the 'ace_config' is applied only from 'file-a.yaml' and the other one is overwritten. That's the exact issue, but there are no errors.

As an workaround, i've commented out the below line from 
> '/netcentric/cq/tools/actool/aceservice/impl/AceServiceImpl.java'

`//removeAcesForAuthorizables(history, session, authorizablesToRemoveAcesFor, repositoryDumpAceMap);`

After that the permission of existing group is preserved with multiple yaml file uploads. I'm not sure that, this is the correct way of doing it.

There is one more issue with file uploading, if the file upload order is changed, then it will not process the yaml config files, because 'group_config' is not defined in 'file-a.yaml'. 

Thanks for looking at the issue and please let me know if you need more information in debugging this issue.

[yaml-config.zip](https://github.com/Netcentric/accesscontroltool/files/214331/yaml-config.zip)

**Comment by gruberroland-netcentric** [comment]
Hi,
the problem is that your file-a.yml has an ace_config for a group in file-b.yaml. This is not supported.
There is also a hint in the readme: "Only ACEs for groups which are defined in the same configuration file can be installed! This ensures a consistency between the groups and their ACE definitions per configuration file."

So you need to edit the ace_config to only contain groups of the current file.

**Comment by santhoshs** [comment]
Thanks for the update!
