### ISSUE TITLE
Only one path to the ACE configurations can be configured

### ISSUE THREAD

**Issue by sbrinkmann** [Netcentric/accesscontroltool#7]
The current design of the __Access Control Tool__ allows to configure only one JCR path where the ACE configuration files are held.

![image](https://cloud.githubusercontent.com/assets/626864/5797897/acb1b004-9fc1-11e4-9d93-c1aa391727a4.png)

In order to use AEM for multiple tenants it is necessary to define an independent path to the ACE configuration of each tenant. Since it is not possible to configure all possible pathes to all tenants in one OSGi configuration, it should be possible to ship the OSGi configuration per tenant. One example for this principle is the configuration of the _Apache Sling Logging Logger Configuration_

![image](https://cloud.githubusercontent.com/assets/626864/5797987/e5c53a9a-9fc2-11e4-978e-23e701085df6.png)

**Comment by ghenzler** [comment]
@sbrinkmann the location as configured via OSGI is only the base path, underneath multiple projects (or tenants) can be configured. See https://github.com/Netcentric/accesscontroltool#storage-of-configurations-in-crx
