### ISSUE TITLE
AcTool bundle doesn't start under AEM 6.2

### ISSUE THREAD

**Issue by santiagozky** [Netcentric/accesscontroltool#78]
The access control tool bundle won't  start due to an unresolved package import com.day.cq.common. 

The current release imports versions [5.6,6), but AEM 6.2 exports the package in version 6.0.

**Comment by santiagozky** [comment]
I created a PR to deal with this:
https://github.com/Netcentric/accesscontroltool/pull/79
it increases the import range for the involved packages to include 6.0

**Comment by ghenzler** [comment]
Merged https://github.com/Netcentric/accesscontroltool/pull/79
