### ISSUE TITLE
get rid of cq-commons dependency

### ISSUE THREAD

**Issue by jochenkoschorke** [Netcentric/accesscontroltool#82]
In the context of #78 and #80 this is a follow up issue which is about removing the dependency to cq-commons completely. Therefore the use of JcrUtil in  biz.netcentric.cq.tools.actool.installationhistory.impl.AcHistoryServiceImpl.persistInstalledConfigurations

as well as JCR constants from cq-commons used in biz.netcentric.cq.tools.actool.configreader.YamlMacroChildNodeObjectsProviderImpl should be replaced

**Comment by kwin** [comment]
The constants are always inlined, therefore they do no lead to a run time dependency (and an import-package statement). So if there are no other suitable constants, just continue to use those.

**Comment by ghenzler** [comment]
mvn dependency is still there for compilation, but runtime dependency is eliminated (no Import-Package for package in manifest)
