### ISSUE TITLE
In case of corrupted oak indexes AC Tool produces NullPointerException instead of usefull error message as output results

### ISSUE THREAD

**Issue by mtstv** [Netcentric/accesscontroltool#95]
In case of corrupted oak indexes AC Tool produces NullPointerException instead of usefull error message as output results.

In case of the next error "500 OakConstraint0030: Uniqueness constraint violated at path [/] for one of the property in [rep:authorizableId] having value etc-cloudservices-brand-ca" AC Tool result with NullPointerException as output result in the JMX console.

I prefer an usefull message like "Can't remove authorizable etc-cloudservices-brand-ca from the system!" instead of broken result output with NullPointerException in the JMX console.

**Comment by ghenzler** [comment]
Merged https://github.com/Netcentric/accesscontroltool/pull/96, thanks @mtstv for the fix.
